"""Shared helpers for generated API tests.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; regenerate after updating api-docs/API_File.
"""

from __future__ import annotations

import csv
import json
import os
import re
from pathlib import Path
from typing import Any

import httpx
import pytest


ROOT_DIR = Path(__file__).resolve().parents[2]
DEFAULT_TIMEOUT = float(os.getenv("API_TEST_TIMEOUT", "30"))


def load_runtime_config() -> dict[str, str]:
    config: dict[str, str] = {}
    config.update(_read_dotenv(ROOT_DIR / ".env"))

    env_name = (
        os.getenv("API_TEST_ENV")
        or os.getenv("ENV")
        or config.get("ENV")
        or "uat"
    )
    config.update(_read_postman_environment(ROOT_DIR / "environments" / f"{env_name}.json"))

    for key, value in list(config.items()):
        if value is not None:
            config.setdefault(key.upper(), str(value))

    return config


def _read_dotenv(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}

    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values.setdefault(key.strip(), value.strip().strip('"').strip("'"))
    return values


def _read_postman_environment(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}

    with path.open(encoding="utf-8") as handle:
        payload = json.load(handle)

    values: dict[str, str] = {}
    for item in payload.get("values", []):
        if item.get("enabled") is False:
            continue
        key = item.get("key")
        if key:
            values.setdefault(str(key), str(item.get("value", "")))
    return values


def perform_api_request(api: dict[str, str], config: dict[str, str]) -> httpx.Response:
    context = dict(config)
    context.update(_first_iteration_data(api))
    request_parameters = _parse_request_parameters(api.get("Request Parameters", ""))

    for key, value in request_parameters["path_variables"].items():
        if value:
            context.setdefault(key, value)

    base_url = _resolve_templates(api.get("Base URL", ""), context).rstrip("/")
    endpoint = _resolve_templates(api.get("Endpoint / Path", ""), context)
    method = (api.get("HTTP Method") or "GET").upper()

    if not base_url or not endpoint:
        pytest.skip("Base URL or endpoint is missing in API file")

    if _has_unresolved_template(base_url) or _has_unresolved_template(endpoint):
        pytest.skip(f"Unresolved URL template in {base_url}{endpoint}")

    url = f"{base_url}/{endpoint.lstrip('/')}"
    headers = _build_headers(api, request_parameters, context)
    params = {
        key: _resolve_templates(value, context)
        for key, value in request_parameters["query"].items()
        if key
    }

    body_text = _resolve_templates(api.get("Request Body", ""), context)
    if _has_unresolved_template(body_text):
        pytest.skip("Request body contains unresolved template variables")

    request_kwargs: dict[str, Any] = {
        "headers": headers,
        "params": params,
        "timeout": DEFAULT_TIMEOUT,
    }

    if body_text:
        parsed_json = _parse_json_safely(body_text)
        if parsed_json is not None and _is_json_request(headers, body_text):
            request_kwargs["json"] = parsed_json
        else:
            request_kwargs["content"] = body_text

    with httpx.Client() as client:
        return client.request(method, url, **request_kwargs)


def _first_iteration_data(api: dict[str, str]) -> dict[str, str]:
    comments = api.get("Comments", "")
    match = re.search(r"Data-driven:\s*([^;]+)", comments)
    if not match:
        return {}

    data_path = ROOT_DIR / match.group(1).strip()
    if not data_path.exists():
        return {}

    with data_path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        first_row = next(reader, None)
        return {key: value for key, value in (first_row or {}).items() if value}


def _parse_request_parameters(raw_parameters: str) -> dict[str, Any]:
    parsed: dict[str, Any] = {
        "headers": {},
        "query": {},
        "path_variables": {},
        "auth": "",
    }

    for section in [part.strip() for part in raw_parameters.split("|") if part.strip()]:
        if ":" not in section:
            continue
        label, value = section.split(":", 1)
        label = label.strip().lower()
        value = value.strip()

        if label == "headers":
            parsed["headers"].update(_parse_key_values(value, separator=";"))
        elif label == "query":
            parsed["query"].update(_parse_key_values(value, separator=";"))
        elif label == "path variables":
            parsed["path_variables"].update(_parse_key_values(value, separator=";"))
        elif label == "auth":
            parsed["auth"] = value

    return parsed


def _parse_key_values(raw_value: str, separator: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for part in [item.strip() for item in raw_value.split(separator) if item.strip()]:
        if "=" in part:
            key, value = part.split("=", 1)
            values[key.strip()] = value.strip()
        else:
            values[part] = ""
    return values


def _build_headers(
    api: dict[str, str],
    request_parameters: dict[str, Any],
    context: dict[str, str],
) -> dict[str, str]:
    headers = {
        key: _resolve_templates(value, context)
        for key, value in request_parameters["headers"].items()
        if key
    }

    if _requires_auth_token(api, request_parameters):
        token = _auth_token(context)
        assert token, (
            "Missing required auth credential: API requires authToken; "
            "set AUTH_TOKEN, API_AUTH_TOKEN, or authToken before running generated tests"
        )
        headers["Authorization"] = f"Bearer {token}"

    for key, value in list(headers.items()):
        if _has_unresolved_template(value):
            if "authtoken" in value.lower():
                token = _auth_token(context)
                assert token, (
                    f"Missing required auth credential: Header {key} "
                    "contains unresolved authToken"
                )
                headers[key] = re.sub(r"\{\{\s*authToken\s*}}", token, value)
            else:
                pytest.skip(f"Header {key} contains unresolved template")

    return headers


def _requires_auth_token(api: dict[str, str], request_parameters: dict[str, Any]) -> bool:
    dependency_text = api.get("Dependent APIs / Services", "")
    parameter_text = api.get("Request Parameters", "")
    return (
        "Requires authToken" in dependency_text
        or "{{authToken}}" in parameter_text
        or "bearer token={{authToken}}" in request_parameters.get("auth", "")
    )


def _auth_token(context: dict[str, str]) -> str:
    for key in ("AUTH_TOKEN", "API_AUTH_TOKEN", "authToken", "AUTHTOKEN"):
        value = os.getenv(key) or context.get(key)
        if value:
            return value
    return ""


def _resolve_templates(value: str, context: dict[str, str]) -> str:
    text = "" if value is None else str(value)

    def replace(match: re.Match[str]) -> str:
        key = match.group(1).strip()
        return (
            os.getenv(key)
            or os.getenv(key.upper())
            or context.get(key)
            or context.get(key.upper())
            or match.group(0)
        )

    return re.sub(r"\{\{\s*([^}]+?)\s*}}", replace, text)


def _has_unresolved_template(value: str) -> bool:
    return "{{" in value and "}}" in value


def _is_json_request(headers: dict[str, str], body_text: str) -> bool:
    content_type = next(
        (value for key, value in headers.items() if key.lower() == "content-type"),
        "",
    )
    return "json" in content_type.lower() or body_text.strip().startswith(("{", "["))


def _parse_json_safely(value: str) -> Any | None:
    try:
        return json.loads(value)
    except json.JSONDecodeError:
        return None


def assert_response_matches_schema(response: httpx.Response, api: dict[str, str]) -> None:
    response_spec = api.get("Response (example/200)", "")
    expected_schema = _schema_from_response_spec(response_spec)

    if expected_schema is None:
        pytest.skip("API file does not define a JSON response schema/example")

    try:
        actual_json = response.json()
    except ValueError as error:
        pytest.fail(f"Expected JSON response matching API file schema: {error}")

    errors: list[str] = []
    _validate_schema(actual_json, expected_schema, "$", errors)
    assert not errors, "Response schema mismatch: " + "; ".join(errors)


def skip_if_no_response_schema(api: dict[str, str]) -> None:
    response_spec = api.get("Response (example/200)", "")
    if _schema_from_response_spec(response_spec) is None:
        pytest.skip("API file does not define a JSON response schema/example")


def _schema_from_response_spec(response_spec: str) -> Any | None:
    parsed = _extract_json_payload(response_spec)
    if parsed is None:
        return None

    return _infer_schema(parsed)


def _extract_json_payload(text: str) -> Any | None:
    if not text:
        return None

    candidates = [text]
    for start_char, end_char in (("{", "}"), ("[", "]")):
        start = text.find(start_char)
        end = text.rfind(end_char)
        if start != -1 and end > start:
            candidates.append(text[start : end + 1])

    for candidate in candidates:
        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            continue
    return None


def _infer_schema(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: _infer_schema(child) for key, child in value.items()}
    if isinstance(value, list):
        return [_infer_schema(value[0])] if value else []
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, int) and not isinstance(value, bool):
        return "integer"
    if isinstance(value, float):
        return "number"
    return "string"


def _validate_schema(actual: Any, expected: Any, path: str, errors: list[str]) -> None:
    if isinstance(expected, dict):
        if not isinstance(actual, dict):
            errors.append(f"{path} expected object")
            return
        for key, child_schema in expected.items():
            if key not in actual:
                errors.append(f"{path}.{key} missing")
                continue
            _validate_schema(actual[key], child_schema, f"{path}.{key}", errors)
        return

    if isinstance(expected, list):
        if not isinstance(actual, list):
            errors.append(f"{path} expected array")
            return
        if expected:
            for index, item in enumerate(actual):
                _validate_schema(item, expected[0], f"{path}[{index}]", errors)
        return

    expected_type = str(expected)
    if expected_type == "integer" and isinstance(actual, int) and not isinstance(actual, bool):
        return
    if expected_type == "number" and isinstance(actual, (int, float)) and not isinstance(actual, bool):
        return
    if expected_type == "string" and isinstance(actual, str):
        return
    if expected_type == "boolean" and isinstance(actual, bool):
        return
    if expected_type == "null" and actual is None:
        return
    errors.append(f"{path} expected {expected_type}")
