"""Shared helpers for generated API tests.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; regenerate after updating api-docs/API_File.
"""

from __future__ import annotations

import atexit
import csv
import json
import os
import re
from pathlib import Path
from typing import Any
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

import allure
import httpx
import pytest

from scripts import pinned_tls


ROOT_DIR = Path(__file__).resolve().parents[2]
DEFAULT_TIMEOUT = float(os.getenv("API_TEST_TIMEOUT", "30"))

#: Connecting is a different question from responding. A reachable host
#: completes a TCP handshake in well under a second; one that cannot is not
#: going to become reachable by waiting the full read budget. Kept separate so
#: a genuinely slow API still gets its 30s to answer.
CONNECT_TIMEOUT = float(os.getenv("API_TEST_CONNECT_TIMEOUT", "6"))

REQUEST_TIMEOUT = httpx.Timeout(
    DEFAULT_TIMEOUT,
    connect=CONNECT_TIMEOUT,
)

#: Hosts that failed to connect during this run, and why. Populated on the
#: first failure and consulted before every later request, so an unreachable
#: host costs one timeout for the whole run rather than one per check -- with
#: 22 checks per endpoint that is the difference between seconds and minutes.
#: Process-scoped, so each pytest session starts clean and a host that comes
#: back is retried on the next run.
_UNREACHABLE_HOSTS: dict[str, str] = {}


#: One client for the process so connections are pooled and reused. Rebuilt if
#: it is ever found closed, and closed at exit.
_CLIENT: "httpx.Client | None" = None


def _shared_client() -> "httpx.Client":
    """The pooled client every request goes through.

    Building a client per request threw the connection away each time, so every
    call paid a fresh DNS + TCP + TLS handshake. Measured on a live host that
    is 1156 ms/request against 97 ms pooled -- with 22 checks per endpoint it
    accounts for most of a run's wall-clock.
    """
    global _CLIENT
    if _CLIENT is None or _CLIENT.is_closed:
        _CLIENT = httpx.Client(
            timeout=REQUEST_TIMEOUT,
            limits=httpx.Limits(max_keepalive_connections=20, max_connections=40),
        )
        atexit.register(_close_shared_client)
    return _CLIENT


def _close_shared_client() -> None:
    global _CLIENT
    if _CLIENT is not None and not _CLIENT.is_closed:
        _CLIENT.close()
    _CLIENT = None


def _host_key(url: "httpx.URL | str") -> str:
    try:
        parsed = url if isinstance(url, httpx.URL) else httpx.URL(str(url))
        return f"{parsed.scheme}://{parsed.netloc.decode('ascii', 'replace')}"
    except Exception:
        return str(url)
REDACTED = "***REDACTED***"
SENSITIVE_KEY_PATTERN = re.compile(
    r"emp[_.-]*code|emp[_.-]*password|password|secret|token",
    re.IGNORECASE,
)
SENSITIVE_HEADER_NAMES = {
    "authorization",
    "proxy-authorization",
    "cookie",
    "set-cookie",
}


def _canonical_env_key(key: str) -> str:
    """Convert Postman-style camelCase names to canonical ENV_VAR names."""
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", key).replace("-", "_").upper()


def load_runtime_config() -> dict[str, str]:
    config: dict[str, str] = {}
    config.update(_read_dotenv(ROOT_DIR / ".env"))

    env_name = (
        os.getenv("API_TEST_ENV")
        or os.getenv("ENV")
        or config.get("ENV")
        or "uat"
    )
    config.update(_read_postman_environment(ROOT_DIR / "environments" / f"{env_name}.json"))

    for key, value in list(config.items()):
        if value is not None:
            config.setdefault(_canonical_env_key(key), str(value))

    return config


def _read_dotenv(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}

    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8-sig").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values.setdefault(key.strip(), value.strip().strip('"').strip("'"))
    return values


def _read_postman_environment(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}

    with path.open(encoding="utf-8-sig") as handle:
        payload = json.load(handle)

    values: dict[str, str] = {}
    for item in payload.get("values", []):
        if item.get("enabled") is False:
            continue
        key = item.get("key")
        if key:
            values.setdefault(str(key), str(item.get("value", "")))
    return values


def _sensitive_values(context: dict[str, str]) -> tuple[str, ...]:
    values = {
        str(value)
        for key, value in context.items()
        if SENSITIVE_KEY_PATTERN.search(str(key)) and value
    }
    return tuple(sorted(values, key=len, reverse=True))


def _redact_text(value: Any, sensitive_values: tuple[str, ...]) -> str:
    redacted = "" if value is None else str(value)
    for sensitive_value in sensitive_values:
        redacted = redacted.replace(sensitive_value, REDACTED)
    redacted = re.sub(
        r"""(?ix)
        (\b(?:emp[_.-]*code|emp[_.-]*password|password|secret|token)\b\s*(?:=|:)\s*)
        (?:"[^"]*"|'[^']*'|[^,;\s&]+)
        """,
        lambda match: f"{match.group(1)}{REDACTED}",
        redacted,
    )
    return re.sub(
        r"(?i)\bBearer\s+[^\s,;]+",
        f"Bearer {REDACTED}",
        redacted,
    )


def _redact_structured_value(
    value: Any,
    sensitive_values: tuple[str, ...],
) -> Any:
    if isinstance(value, dict):
        return {
            key: (
                REDACTED
                if SENSITIVE_KEY_PATTERN.search(str(key))
                else _redact_structured_value(child, sensitive_values)
            )
            for key, child in value.items()
        }
    if isinstance(value, list):
        return [
            _redact_structured_value(child, sensitive_values)
            for child in value
        ]
    if isinstance(value, str):
        return _redact_text(value, sensitive_values)
    return value


def _redacted_headers(
    headers: httpx.Headers,
    sensitive_values: tuple[str, ...],
) -> dict[str, str]:
    redacted: dict[str, str] = {}
    for key, value in headers.multi_items():
        normalized_key = key.lower()
        if normalized_key == "authorization" and value.lower().startswith("bearer "):
            safe_value = f"Bearer {REDACTED}"
        elif (
            normalized_key in SENSITIVE_HEADER_NAMES
            or SENSITIVE_KEY_PATTERN.search(normalized_key)
        ):
            safe_value = REDACTED
        else:
            safe_value = _redact_text(value, sensitive_values)
        redacted[key] = safe_value
    return redacted


def _redacted_url(
    url: httpx.URL,
    sensitive_values: tuple[str, ...],
) -> str:
    parsed = urlsplit(str(url))
    safe_query = urlencode(
        [
            (
                key,
                REDACTED
                if SENSITIVE_KEY_PATTERN.search(key)
                else _redact_text(value, sensitive_values),
            )
            for key, value in parse_qsl(parsed.query, keep_blank_values=True)
        ],
        doseq=True,
    )
    safe_netloc = parsed.netloc
    if parsed.username is not None or parsed.password is not None:
        host = parsed.hostname or ""
        port = f":{parsed.port}" if parsed.port is not None else ""
        safe_netloc = f"{REDACTED}@{host}{port}"
    return urlunsplit(
        (
            parsed.scheme,
            safe_netloc,
            _redact_text(parsed.path, sensitive_values),
            safe_query,
            _redact_text(parsed.fragment, sensitive_values),
        )
    )


def _redacted_body(
    content: bytes,
    content_type: str,
    sensitive_values: tuple[str, ...],
) -> tuple[str, Any]:
    if not content:
        return "<empty>", allure.attachment_type.TEXT

    decoded = content.decode("utf-8", errors="replace")
    parsed_json = _parse_json_safely(decoded)
    if parsed_json is not None:
        return (
            json.dumps(
                _redact_structured_value(parsed_json, sensitive_values),
                indent=2,
            ),
            allure.attachment_type.JSON,
        )

    if "application/x-www-form-urlencoded" in content_type.lower():
        safe_form = [
            (
                key,
                REDACTED
                if SENSITIVE_KEY_PATTERN.search(key)
                else _redact_text(value, sensitive_values),
            )
            for key, value in parse_qsl(decoded, keep_blank_values=True)
        ]
        return urlencode(safe_form), allure.attachment_type.TEXT

    return (
        f"<non-JSON body omitted from report; {len(content)} bytes>",
        allure.attachment_type.TEXT,
    )


def _attach_request(
    request: httpx.Request,
    sensitive_values: tuple[str, ...],
) -> None:
    safe_body, body_type = _redacted_body(
        request.content,
        request.headers.get("content-type", ""),
        sensitive_values,
    )
    allure.attach(
        request.method,
        name="Request Method",
        attachment_type=allure.attachment_type.TEXT,
    )
    allure.attach(
        _redacted_url(request.url, sensitive_values),
        name="Request URL",
        attachment_type=allure.attachment_type.TEXT,
    )
    allure.attach(
        json.dumps(_redacted_headers(request.headers, sensitive_values), indent=2),
        name="Request Headers",
        attachment_type=allure.attachment_type.JSON,
    )
    allure.attach(
        safe_body,
        name="Request Body",
        attachment_type=body_type,
    )


def _attach_response(
    response: httpx.Response,
    sensitive_values: tuple[str, ...],
) -> None:
    safe_body, body_type = _redacted_body(
        response.content,
        response.headers.get("content-type", ""),
        sensitive_values,
    )
    allure.attach(
        str(response.status_code),
        name="Response Status",
        attachment_type=allure.attachment_type.TEXT,
    )
    allure.attach(
        json.dumps(_redacted_headers(response.headers, sensitive_values), indent=2),
        name="Response Headers",
        attachment_type=allure.attachment_type.JSON,
    )
    allure.attach(
        safe_body,
        name="Response Body",
        attachment_type=body_type,
    )


def perform_api_request(api: dict[str, str], config: dict[str, str]) -> httpx.Response:
    context = dict(config)
    context.update(_first_iteration_data(api))
    request_parameters = _parse_request_parameters(api.get("Request Parameters", ""))

    for key, value in request_parameters["path_variables"].items():
        if value:
            context.setdefault(key, value)

    base_url = _resolve_templates(api.get("Base URL", ""), context).rstrip("/")
    endpoint = _resolve_templates(api.get("Endpoint / Path", ""), context)
    method = (api.get("HTTP Method") or "GET").upper()

    if not base_url or not endpoint:
        pytest.skip("Base URL or endpoint is missing in API file")

    if _has_unresolved_template(base_url) or _has_unresolved_template(endpoint):
        pytest.skip(f"Unresolved URL template in {base_url}{endpoint}")

    # Only now: the inner half of an unresolved `{{name}}` is itself a valid
    # single-brace match, so substituting before the guard above could rewrite
    # `{{baseURL}}` into `{value}` and slip a mangled URL past the very check
    # meant to catch it.
    endpoint = _resolve_path_parameters(endpoint, context)

    # A path parameter left unresolved would be percent-encoded onto the wire,
    # and the container rejects it with 400 before routing. Every assertion
    # downstream would then be judging a malformed request, not the API.
    unresolved_path_parameters = _unresolved_path_parameters(endpoint)
    if unresolved_path_parameters:
        pytest.skip(
            "No value supplied for path parameter(s) "
            + ", ".join(unresolved_path_parameters)
        )

    url = f"{base_url}/{endpoint.lstrip('/')}"
    headers = _build_headers(api, request_parameters, context)
    params = {
        key: _resolve_templates(value, context)
        for key, value in request_parameters["query"].items()
        if key
    }

    body_text = _resolve_templates(api.get("Request Body", ""), context)
    if _has_unresolved_template(body_text):
        pytest.skip("Request body contains unresolved template variables")

    request_kwargs: dict[str, Any] = {
        "headers": headers,
        "params": params,
        "timeout": REQUEST_TIMEOUT,
    }

    if body_text:
        parsed_json = _parse_json_safely(body_text)
        if parsed_json is not None and _is_json_request(headers, body_text):
            request_kwargs["json"] = parsed_json
        else:
            request_kwargs["content"] = body_text

    down = _UNREACHABLE_HOSTS.get(_host_key(url))
    if down:
        # Already proven unreachable in this run. Waiting again would cost
        # another connect timeout to learn the same thing.
        pytest.skip(down)

    client = _shared_client()
    # Every request must look like the first this client ever sent. Without
    # this, a session cookie set by an authenticated call would ride along into
    # the checks asserting an anonymous caller is refused, and they would pass
    # for the wrong reason.
    client.cookies.clear()

    request = client.build_request(method, url, **request_kwargs)
    sensitive_values = _sensitive_values(context)
    _attach_request(request, sensitive_values)
    try:
        if _uses_pinned_tls(request.url):
            response = _send_pinned_request(request)
        else:
            response = client.send(request)
    except Exception as error:
        safe_message = _redact_text(str(error), sensitive_values)
        allure.attach(
            f"{type(error).__module__}.{type(error).__name__}: {safe_message}",
            name="Request Exception",
            attachment_type=allure.attachment_type.TEXT,
        )
        if isinstance(error, (httpx.ConnectError, httpx.ConnectTimeout)):
            # The host never accepted a connection, so no contract was
            # exercised. That is an untested endpoint, not a broken one --
            # calling it a failure blames the API for the environment.
            # Remembered so the remaining checks on this host return at
            # once instead of each paying the same timeout.
            # The bracketed token is what the summary counts on. Matching the
            # English sentence would break the first time someone reworded it.
            reason = (
                f"host {_host_key(request.url)} is unreachable "
                f"({type(error).__name__}); "
                f"every check on it is untested, not failed "
                f"[host=unreachable]"
            )
            _UNREACHABLE_HOSTS[_host_key(request.url)] = reason
            pytest.skip(reason)
        raise

    _attach_response(response, sensitive_values)
    return response


def _uses_pinned_tls(url: httpx.URL) -> bool:
    """Select the fixed-host pin without weakening TLS for any other origin."""
    return (
        url.scheme == "https"
        and url.host == pinned_tls.PINNED_HOST
        and url.port in (None, pinned_tls.PINNED_PORT)
    )


def _send_pinned_request(request: httpx.Request) -> httpx.Response:
    pinned_response = pinned_tls.request(
        request.method,
        request.url.raw_path.decode("ascii"),
        headers=dict(request.headers),
        content=request.content,
        timeout=CONNECT_TIMEOUT + DEFAULT_TIMEOUT,
    )
    return httpx.Response(
        status_code=pinned_response.status_code,
        headers=pinned_response.headers,
        content=pinned_response.content,
        request=request,
        extensions={"reason_phrase": pinned_response.reason.encode("ascii", errors="replace")},
    )


def _first_iteration_data(api: dict[str, str]) -> dict[str, str]:
    comments = api.get("Comments", "")
    match = re.search(r"Data-driven:\s*([^;]+)", comments)
    if not match:
        return {}

    data_path = ROOT_DIR / match.group(1).strip()
    if not data_path.exists():
        return {}

    with data_path.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        first_row = next(reader, None)
        return {key: value for key, value in (first_row or {}).items() if value}


def _parse_request_parameters(raw_parameters: str) -> dict[str, Any]:
    parsed: dict[str, Any] = {
        "headers": {},
        "query": {},
        "path_variables": {},
        "auth": "",
    }

    for section in [part.strip() for part in raw_parameters.split("|") if part.strip()]:
        if ":" not in section:
            continue
        label, value = section.split(":", 1)
        label = label.strip().lower()
        value = value.strip()

        if label == "headers":
            parsed["headers"].update(_parse_key_values(value, separator=";"))
        elif label == "query":
            parsed["query"].update(_parse_key_values(value, separator=";"))
        elif label == "path variables":
            parsed["path_variables"].update(_parse_key_values(value, separator=";"))
        elif label == "auth":
            parsed["auth"] = value

    return parsed


def _parse_key_values(raw_value: str, separator: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for part in [item.strip() for item in raw_value.split(separator) if item.strip()]:
        if "=" in part:
            key, value = part.split("=", 1)
            values[key.strip()] = value.strip()
        else:
            values[part] = ""
    return values


def _build_headers(
    api: dict[str, str],
    request_parameters: dict[str, Any],
    context: dict[str, str],
) -> dict[str, str]:
    headers = {
        key: _resolve_templates(value, context)
        for key, value in request_parameters["headers"].items()
        if key
    }

    suppress = bool(context.get("__suppress_auth__"))
    if suppress:
        # Drop anything already carrying a credential, so a row that hardcodes
        # an Authorization header cannot smuggle one past the suppression.
        headers = {k: v for k, v in headers.items() if k.lower() != "authorization"}

    if _requires_auth_token(api, request_parameters, context):
        token = _auth_token(context)
        assert token, (
            "Missing required auth credential: API requires authToken; "
            "set AUTH_TOKEN, API_AUTH_TOKEN, or authToken before running generated tests"
        )
        headers["Authorization"] = f"Bearer {token}"

    for key, value in list(headers.items()):
        if _has_unresolved_template(value):
            if "authtoken" in value.lower() and not suppress:
                token = _auth_token(context)
                assert token, (
                    f"Missing required auth credential: Header {key} "
                    "contains unresolved authToken"
                )
                headers[key] = re.sub(r"\{\{\s*authToken\s*}}", token, value)
            else:
                pytest.skip(f"Header {key} contains unresolved template")

    return headers


def _requires_auth_token(
    api: dict[str, str],
    request_parameters: dict[str, Any],
    context: dict[str, str] | None = None,
) -> bool:
    # The anonymous-access check needs a request that carries no credential at
    # all. Clearing the header columns is not enough on its own, because this
    # predicate also reads the dependency column, which that check leaves
    # intact -- so without this the "anonymous" request went out authenticated
    # and its result described nothing.
    if context and context.get("__suppress_auth__"):
        return False
    dependency_text = api.get("Dependent APIs / Services", "")
    parameter_text = api.get("Request Parameters", "")
    return (
        "Requires authToken" in dependency_text
        or "{{authToken}}" in parameter_text
        or "bearer token={{authToken}}" in request_parameters.get("auth", "")
    )


def _auth_token(context: dict[str, str]) -> str:
    """Return the bearer token for authenticated requests.

    The session bootstrap in conftest.py mints a fresh token and writes it into
    ``context``. That value must win over any ambient AUTH_TOKEN/API_AUTH_TOKEN
    left in the process environment, because a stale export or CI secret would
    otherwise silently defeat the bootstrap and surface as unexplained 401s.
    The process environment stays available as a fallback for the case where no
    bootstrapped value is present.
    """
    keys = ("AUTH_TOKEN", "API_AUTH_TOKEN", "authToken", "AUTHTOKEN")
    for lookup in (context.get, os.getenv):
        for key in keys:
            value = lookup(key)
            if value:
                return value
    return ""


def _resolve_templates(value: str, context: dict[str, str]) -> str:
    text = "" if value is None else str(value)

    def replace(match: re.Match[str]) -> str:
        key = match.group(1).strip()
        canonical_key = _canonical_env_key(key)

        # Canonical snake-case values are explicit runtime overrides. Check
        # both process and dotenv context before camelCase Postman defaults so
        # baseUrl cannot collide with the legacy BASEURL spelling.
        for candidate in (canonical_key, key, key.upper()):
            resolved = os.getenv(candidate) or context.get(candidate)
            if resolved:
                return resolved

        return match.group(0)

    return re.sub(r"\{\{\s*([^}]+?)\s*}}", replace, text)


def _has_unresolved_template(value: str) -> bool:
    return "{{" in value and "}}" in value


#: An OpenAPI-style path parameter: a single-brace token that is not part of a
#: Postman `{{variable}}`. Matched after `_resolve_templates` has run, so any
#: surviving double-brace pair is a separate problem already reported above.
_PATH_PARAMETER_RE = re.compile(r"\{([^{}]+)\}")


def _resolve_path_parameters(endpoint: str, context: dict[str, str]) -> str:
    """Fill `/orders/{orderId}` from the same context `{{orderId}}` would use.

    Left alone by `_resolve_templates`, which only understands double braces.
    Unresolved names are returned untouched so the caller can skip on them
    rather than sending a URL the container will reject.
    """

    def replace(match: re.Match[str]) -> str:
        key = match.group(1).strip()
        for candidate in (_canonical_env_key(key), key, key.upper()):
            resolved = os.getenv(candidate) or context.get(candidate)
            if resolved:
                return str(resolved)
        return match.group(0)

    return _PATH_PARAMETER_RE.sub(replace, "" if endpoint is None else str(endpoint))


def _unresolved_path_parameters(endpoint: str) -> list[str]:
    """Path parameter names still present after substitution, in order."""
    return [
        match.group(1).strip()
        for match in _PATH_PARAMETER_RE.finditer(endpoint or "")
    ]


def _is_json_request(headers: dict[str, str], body_text: str) -> bool:
    content_type = next(
        (value for key, value in headers.items() if key.lower() == "content-type"),
        "",
    )
    return "json" in content_type.lower() or body_text.strip().startswith(("{", "["))


def _parse_json_safely(value: str) -> Any | None:
    try:
        return json.loads(value)
    except json.JSONDecodeError:
        return None


def assert_response_matches_schema(response: httpx.Response, api: dict[str, str]) -> None:
    response_spec = api.get("Response (example/200)", "")
    expected_schema = _schema_from_response_spec(response_spec)

    if expected_schema is None:
        pytest.skip("API file does not define a JSON response schema/example")

    try:
        actual_json = response.json()
    except ValueError as error:
        pytest.fail(f"Expected JSON response matching API file schema: {error}")

    errors: list[str] = []
    _validate_schema(actual_json, expected_schema, "$", errors)
    assert not errors, "Response schema mismatch: " + "; ".join(errors)


def skip_if_no_response_schema(api: dict[str, str]) -> None:
    response_spec = api.get("Response (example/200)", "")
    if _schema_from_response_spec(response_spec) is None:
        pytest.skip("API file does not define a JSON response schema/example")


def _schema_from_response_spec(response_spec: str) -> Any | None:
    parsed = _extract_json_payload(response_spec)
    if parsed is None:
        return None

    return _infer_schema(parsed)


def _extract_json_payload(text: str) -> Any | None:
    if not text:
        return None

    candidates = [text]
    for start_char, end_char in (("{", "}"), ("[", "]")):
        start = text.find(start_char)
        end = text.rfind(end_char)
        if start != -1 and end > start:
            candidates.append(text[start : end + 1])

    for candidate in candidates:
        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            continue
    return None


def _infer_schema(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: _infer_schema(child) for key, child in value.items()}
    if isinstance(value, list):
        return [_infer_schema(value[0])] if value else []
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, int) and not isinstance(value, bool):
        return "integer"
    if isinstance(value, float):
        return "number"
    return "string"


def _validate_schema(actual: Any, expected: Any, path: str, errors: list[str]) -> None:
    if isinstance(expected, dict):
        if not isinstance(actual, dict):
            errors.append(f"{path} expected object")
            return
        for key, child_schema in expected.items():
            if key not in actual:
                errors.append(f"{path}.{key} missing")
                continue
            _validate_schema(actual[key], child_schema, f"{path}.{key}", errors)
        return

    if isinstance(expected, list):
        if not isinstance(actual, list):
            errors.append(f"{path} expected array")
            return
        if expected:
            for index, item in enumerate(actual):
                _validate_schema(item, expected[0], f"{path}[{index}]", errors)
        return

    expected_type = str(expected)
    if expected_type == "integer" and isinstance(actual, int) and not isinstance(actual, bool):
        return
    if expected_type == "number" and isinstance(actual, (int, float)) and not isinstance(actual, bool):
        return
    if expected_type == "string" and isinstance(actual, str):
        return
    if expected_type == "boolean" and isinstance(actual, bool):
        return
    if expected_type == "null" and actual is None:
        return
    errors.append(f"{path} expected {expected_type}")
