"""Pytest fixtures for generated API tests.

This file is generated by scripts/generate-generic-tests.py.
"""

from __future__ import annotations

import json
import re

import pytest

from ._api_test_helpers import ROOT_DIR, load_runtime_config, perform_api_request


class _RuntimeConfig(dict[str, str]):
    """Keep credentials out of pytest fixture representations on failures."""

    def __repr__(self) -> str:
        redacted = {
            key: "<redacted>"
            if re.search(r"password|token|secret|api[_-]?key|emp[_-]?code", key, re.IGNORECASE)
            else value
            for key, value in self.items()
        }
        return dict.__repr__(redacted)


@pytest.fixture(scope="session")
def api_runtime_config() -> dict[str, str]:
    config = _RuntimeConfig(load_runtime_config())
    with (ROOT_DIR / "api-docs" / "API_File.json").open(encoding="utf-8-sig") as handle:
        api_rows = json.load(handle)

    auth_row = next(
        row
        for row in api_rows
        if row.get("Module Name") == "Employee Auth API"
        and row.get("HTTP Method") == "POST"
        and row.get("Endpoint / Path") == "/auth/token"
        and re.search(
            r"Expected status\(es\):[^\n]*\b2\d\d\b",
            row.get("Response (example/200)", ""),
        )
    )
    response = perform_api_request(auth_row, config)
    assert response.is_success, (
        f"Employee Auth bootstrap returned {response.status_code}; "
        "response body withheld"
    )

    payload = response.json()
    token = None
    if isinstance(payload, dict):
        token = payload.get("token") or payload.get("access_token") or payload.get("authToken")
        if not token and isinstance(payload.get("data"), dict):
            token = payload["data"].get("token") or payload["data"].get("access_token") or payload["data"].get("authToken")
            
    assert token, "Employee Auth bootstrap response did not contain a token"
    config.update(
        {
            "AUTH_TOKEN": token,
            "API_AUTH_TOKEN": token,
            "authToken": token,
        }
    )
    return config
