"""Pytest fixtures for generated API tests.

This file is generated by scripts/generate-generic-tests.py.
"""

from __future__ import annotations

import pytest

from ._api_test_helpers import load_runtime_config


@pytest.fixture(scope="session")
def api_runtime_config() -> dict[str, str]:
    return load_runtime_config()
