"""Generated tests for API row 8.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "8",
  "Module Name": "Attendance Policy Master",
  "Sub-Module Name": "Get All Policies",
  "Access": "private",
  "Functional Purpose": "Get All Policies",
  "Base URL": "{{baseURL}}",
  "Endpoint / Path": "/api/attendancepolicy",
  "HTTP Method": "GET",
  "Request Parameters": "headers: Authorization=Bearer {{authToken}}",
  "Request Body": "",
  "Example Request Payload": "",
  "Request Body Schema": "",
  "Response (example/200)": "",
  "Example Response Payload": "",
  "Dependent APIs / Services": "Requires authToken from Employee Auth API; Depends on Employee Auth API POST /auth/token for authToken",
  "Owner / Developer": "",
  "API Identifier": "get|/api/attendancepolicy|attendance policy master|get all policies",
  "Comments": "Source: collections/Attendance_Management_API.json; No saved response example in source file"
}""")

@allure.title("Get All Policies \u2014 returns HTTP 200")
@allure.epic("Attendance Policy Master")
@allure.feature("GET /api/attendancepolicy — Get All Policies")
@allure.story("HTTP Status Code Check (200)")
@allure.parent_suite("Attendance Policy Master")
@allure.suite("GET /api/attendancepolicy — Get All Policies")
@allure.sub_suite("HTTP Status Code Check (200)")
@allure.label("sourceModule", "Attendance Policy Master")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("get|/api/attendancepolicy|attendance policy master|get all policies", name="API Identifier")
@pytest.mark.skip(reason="Temporarily disabled per user request due to negative scenario mismatch")
def test_attendance_policy_master_api_attendancepolicy_status_code(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "GET")
    allure.dynamic.parameter("Endpoint Path", "/api/attendancepolicy")
    allure.dynamic.parameter("Expected Status", "200")
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


@allure.title("Get All Policies \u2014 response matches documented schema")
@allure.epic("Attendance Policy Master")
@allure.feature("GET /api/attendancepolicy — Get All Policies")
@allure.story("OpenAPI Schema Validation Check")
@allure.parent_suite("Attendance Policy Master")
@allure.suite("GET /api/attendancepolicy — Get All Policies")
@allure.sub_suite("OpenAPI Schema Validation Check")
@allure.label("sourceModule", "Attendance Policy Master")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("get|/api/attendancepolicy|attendance policy master|get all policies", name="API Identifier")
@pytest.mark.skip(reason="Temporarily disabled per user request due to negative scenario mismatch")
def test_attendance_policy_master_api_attendancepolicy_response_schema(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "GET")
    allure.dynamic.parameter("Endpoint Path", "/api/attendancepolicy")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
