"""Generated tests for API row 5.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "5",
  "Module Name": "Login API",
  "Sub-Module Name": "TC01 - Valid credentials return token",
  "Access": "public",
  "Functional Purpose": "TC01 - Valid credentials return token",
  "Base URL": "{{baseUrl}}",
  "Endpoint / Path": "/auth/token",
  "HTTP Method": "POST",
  "Request Parameters": "headers: Content-Type=application/json",
  "Request Body": "{\n  \"empCode\": \"{{empCode}}\",\n  \"password\": \"{{password}}\"\n}",
  "Example Request Payload": "{\n  \"empCode\": \"OMI-0001\",\n  \"password\": \"<password>\"\n}",
  "Request Body Schema": "{\"empCode\":\"string\",\"password\":\"string\"}",
  "Response (example/200)": "Expected status(es): 200\n{\n  \"empCode\": \"<empCode>\",\n  \"roles\": [\n    \"<role>\"\n  ],\n  \"token\": \"<jwt-token>\",\n  \"username\": \"<username>\"\n}",
  "Example Response Payload": "{\n  \"empCode\": \"<empCode>\",\n  \"roles\": [\n    \"<role>\"\n  ],\n  \"token\": \"<jwt-token>\",\n  \"username\": \"<username>\"\n}",
  "Dependent APIs / Services": "Produces authToken for downstream APIs",
  "Owner / Developer": "KavishTadas <kavish.tadas@omfysgroup.com>",
  "API Identifier": "post|{{baseurl}}|/auth/token|login api|tc01 - valid credentials return token",
  "Comments": "Source: collections/Login_API.json; Data-driven: test-data/Login_API.csv; No saved response example in source file"
}""")

def test_login_api_auth_token_status_code(api_runtime_config: dict[str, str]) -> None:
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


def test_login_api_auth_token_response_schema(api_runtime_config: dict[str, str]) -> None:
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
