"""Generated tests for API row 23.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "23",
  "Module Name": "Attendance Status Threshold API",
  "Sub-Module Name": "Get All",
  "Access": "private",
  "Functional Purpose": "Get All",
  "Base URL": "{{baseUrl}}",
  "Endpoint / Path": "/api/attendance/status-threshold/getAll",
  "HTTP Method": "GET",
  "Request Parameters": "query: page=0; size=10; sort=thresholdName,asc | headers: Authorization=Bearer {{token}}",
  "Request Body": "",
  "Example Request Payload": "",
  "Request Body Schema": "",
  "Response (example/200)": "",
  "Example Response Payload": "",
  "Dependent APIs / Services": "",
  "Owner / Developer": "Parth Divekar <parthdivekar987@gmail.com>",
  "API Identifier": "get|/api/attendance/status-threshold/getall|attendance status threshold api|get all",
  "Comments": "Source: collections/Attendance_Threshold_API.json; No saved response example in source file"
}""")

@allure.title("Get All \u2014 returns HTTP 200")
@allure.epic("Attendance Status Threshold API")
@allure.feature("GET /api/attendance/status-threshold/getAll — Get All")
@allure.story("HTTP Status Code Check (200)")
@allure.parent_suite("Attendance Status Threshold API")
@allure.suite("GET /api/attendance/status-threshold/getAll — Get All")
@allure.sub_suite("HTTP Status Code Check (200)")
@allure.label("sourceModule", "Attendance Status Threshold API")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "Parth Divekar <parthdivekar987@gmail.com>")
@allure.link("get|/api/attendance/status-threshold/getall|attendance status threshold api|get all", name="API Identifier")
def test_attendance_status_threshold_api_api_attendance_status_threshold_getall_status_code(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "GET")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/status-threshold/getAll")
    allure.dynamic.parameter("Expected Status", "200")
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


@allure.title("Get All \u2014 response matches documented schema")
@allure.epic("Attendance Status Threshold API")
@allure.feature("GET /api/attendance/status-threshold/getAll — Get All")
@allure.story("OpenAPI Schema Validation Check")
@allure.parent_suite("Attendance Status Threshold API")
@allure.suite("GET /api/attendance/status-threshold/getAll — Get All")
@allure.sub_suite("OpenAPI Schema Validation Check")
@allure.label("sourceModule", "Attendance Status Threshold API")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "Parth Divekar <parthdivekar987@gmail.com>")
@allure.link("get|/api/attendance/status-threshold/getall|attendance status threshold api|get all", name="API Identifier")
def test_attendance_status_threshold_api_api_attendance_status_threshold_getall_response_schema(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "GET")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/status-threshold/getAll")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
