"""Generated tests for API row 21.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "21",
  "Module Name": "Attendance Status Threshold API",
  "Sub-Module Name": "Update Threshold",
  "Access": "private",
  "Functional Purpose": "Update Threshold",
  "Base URL": "{{baseUrl}}",
  "Endpoint / Path": "/api/attendance/status-threshold/update/1",
  "HTTP Method": "PUT",
  "Request Parameters": "headers: Authorization=Bearer {{token}}; Content-Type=application/json",
  "Request Body": "{\n  \"thresholdCode\": \"TH001\",\n  \"thresholdName\": \"Updated Threshold\",\n  \"description\": \"Updated Description\",\n  \"templateMode\": \"DEFAULT\",\n  \"shiftTypeApplicability\": \"ALL\",\n  \"absentMaxHours\": 3.00,\n  \"halfDayMinHours\": 3.01,\n  \"fullDayMinHours\": 5.01,\n  \"presentMinHours\": 5.02,\n  \"effectiveFrom\": \"2027-01-01\",\n  \"effectiveTo\": null,\n  \"isDefault\": \"Y\",\n  \"isActive\": \"Y\",\n  \"templateStatus\": \"DRAFT\",\n  \"remarks\": \"Updated\",\n  \"assignments\": []\n}",
  "Example Request Payload": "{\n  \"thresholdCode\": \"TH001\",\n  \"thresholdName\": \"Updated Threshold\",\n  \"description\": \"Updated Description\",\n  \"templateMode\": \"DEFAULT\",\n  \"shiftTypeApplicability\": \"ALL\",\n  \"absentMaxHours\": 3,\n  \"halfDayMinHours\": 3.01,\n  \"fullDayMinHours\": 5.01,\n  \"presentMinHours\": 5.02,\n  \"effectiveFrom\": \"2027-01-01\",\n  \"effectiveTo\": null,\n  \"isDefault\": \"Y\",\n  \"isActive\": \"Y\",\n  \"templateStatus\": \"DRAFT\",\n  \"remarks\": \"Updated\",\n  \"assignments\": []\n}",
  "Request Body Schema": "{\"thresholdCode\":\"string\",\"thresholdName\":\"string\",\"description\":\"string\",\"templateMode\":\"string\",\"shiftTypeApplicability\":\"string\",\"absentMaxHours\":\"number\",\"halfDayMinHours\":\"number\",\"fullDayMinHours\":\"number\",\"presentMinHours\":\"number\",\"effectiveFrom\":\"string\",\"effectiveTo\":\"null\",\"isDefault\":\"string\",\"isActive\":\"string\",\"templateStatus\":\"string\",\"remarks\":\"string\",\"assignments\":[]}",
  "Response (example/200)": "",
  "Example Response Payload": "",
  "Dependent APIs / Services": "",
  "Owner / Developer": "Parth Divekar <parthdivekar987@gmail.com>",
  "API Identifier": "put|/api/attendance/status-threshold/update/1|attendance status threshold api|update threshold",
  "Comments": "Source: collections/Attendance_Threshold_API.json; No saved response example in source file"
}""")

@allure.title("Update Threshold \u2014 returns HTTP 200")
@allure.epic("Attendance Status Threshold API")
@allure.feature("PUT /api/attendance/status-threshold/update/1 — Update Threshold")
@allure.story("HTTP Status Code Check (200)")
@allure.parent_suite("Attendance Status Threshold API")
@allure.suite("PUT /api/attendance/status-threshold/update/1 — Update Threshold")
@allure.sub_suite("HTTP Status Code Check (200)")
@allure.label("sourceModule", "Attendance Status Threshold API")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "Parth Divekar <parthdivekar987@gmail.com>")
@allure.link("put|/api/attendance/status-threshold/update/1|attendance status threshold api|update threshold", name="API Identifier")
def test_attendance_status_threshold_api_api_attendance_status_threshold_update_1_status_code(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "PUT")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/status-threshold/update/1")
    allure.dynamic.parameter("Expected Status", "200")
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


@allure.title("Update Threshold \u2014 response matches documented schema")
@allure.epic("Attendance Status Threshold API")
@allure.feature("PUT /api/attendance/status-threshold/update/1 — Update Threshold")
@allure.story("OpenAPI Schema Validation Check")
@allure.parent_suite("Attendance Status Threshold API")
@allure.suite("PUT /api/attendance/status-threshold/update/1 — Update Threshold")
@allure.sub_suite("OpenAPI Schema Validation Check")
@allure.label("sourceModule", "Attendance Status Threshold API")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "Parth Divekar <parthdivekar987@gmail.com>")
@allure.link("put|/api/attendance/status-threshold/update/1|attendance status threshold api|update threshold", name="API Identifier")
def test_attendance_status_threshold_api_api_attendance_status_threshold_update_1_response_schema(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "PUT")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/status-threshold/update/1")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
