"""Generated tests for API row 19.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "19",
  "Module Name": "Attendance Shift Master",
  "Sub-Module Name": "Get All Shifts",
  "Access": "private",
  "Functional Purpose": "Get All Shifts",
  "Base URL": "{{baseURL}}",
  "Endpoint / Path": "/api/v1/attendance/shift/master",
  "HTTP Method": "GET",
  "Request Parameters": "query: page=0; includeDeleted=true | headers: Authorization=Bearer {{authToken}}",
  "Request Body": "",
  "Example Request Payload": "",
  "Request Body Schema": "",
  "Response (example/200)": "",
  "Example Response Payload": "",
  "Dependent APIs / Services": "Requires authToken from Employee Auth API; Depends on Employee Auth API POST /auth/token for authToken",
  "Owner / Developer": "",
  "API Identifier": "get|/api/v1/attendance/shift/master|attendance shift master|get all shifts",
  "Comments": "Source: collections/Attendance_Management_API.json; No saved response example in source file"
}""")

@allure.title("Get All Shifts \u2014 returns HTTP 200")
@allure.epic("Attendance Shift Master")
@allure.feature("GET /api/v1/attendance/shift/master — Get All Shifts")
@allure.story("HTTP Status Code Check (200)")
@allure.parent_suite("Attendance Shift Master")
@allure.suite("GET /api/v1/attendance/shift/master — Get All Shifts")
@allure.sub_suite("HTTP Status Code Check (200)")
@allure.label("sourceModule", "Attendance Shift Master")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("get|/api/v1/attendance/shift/master|attendance shift master|get all shifts", name="API Identifier")
def test_attendance_shift_master_api_v1_attendance_shift_master_status_code(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "GET")
    allure.dynamic.parameter("Endpoint Path", "/api/v1/attendance/shift/master")
    allure.dynamic.parameter("Expected Status", "200")
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


@allure.title("Get All Shifts \u2014 response matches documented schema")
@allure.epic("Attendance Shift Master")
@allure.feature("GET /api/v1/attendance/shift/master — Get All Shifts")
@allure.story("OpenAPI Schema Validation Check")
@allure.parent_suite("Attendance Shift Master")
@allure.suite("GET /api/v1/attendance/shift/master — Get All Shifts")
@allure.sub_suite("OpenAPI Schema Validation Check")
@allure.label("sourceModule", "Attendance Shift Master")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("get|/api/v1/attendance/shift/master|attendance shift master|get all shifts", name="API Identifier")
def test_attendance_shift_master_api_v1_attendance_shift_master_response_schema(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "GET")
    allure.dynamic.parameter("Endpoint Path", "/api/v1/attendance/shift/master")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
