"""Generated tests for API row 13.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "13",
  "Module Name": "Attendance Shift Master",
  "Sub-Module Name": "Create New Shift",
  "Access": "private",
  "Functional Purpose": "Create New Shift",
  "Base URL": "{{baseURL}}",
  "Endpoint / Path": "/api/v1/attendance/shift/master",
  "HTTP Method": "POST",
  "Request Parameters": "headers: Authorization=Bearer {{authToken}}",
  "Request Body": "{\n  \"shiftCode\": \"SHF-MIDNIGHT-001\",\n  \"shiftName\": \"MidNight Shift - Standard\",\n  \"shiftType\": \"FIXED\",\n  \"applicabilityType\": \"DEFAULT\",\n  \"startTime\": \"09:00:00\",\n  \"endTime\": \"18:00:00\",\n  \"graceMinutes\": 15,\n  \"requiredDurationHours\": null,\n  \"effectiveFrom\": \"01-Aug-2026\",\n  \"effectiveTo\": \"31-Dec-2026\",\n  \"isDeleted\": \"N\",\n  \"description\":\"xyz\",\n  \"remarks\": \"Standard morning shift for all employees\",\n  \"breakConfigs\": [\n    {\n      \"breakName\": \"Lunch Break\",\n      \"breakDurationMinutes\": 60,\n      \"paidFlag\": false\n    },\n    {\n      \"breakName\": \"Tea Break\",\n      \"breakDurationMinutes\": 15,\n      \"paidFlag\": true\n    },\n    {\n      \"breakName\": \"Evening Tea\",\n      \"breakDurationMinutes\": 15,\n      \"paidFlag\": true\n    }\n  ],\n  \"applicableEmpIds\": null\n}",
  "Example Request Payload": "{\n  \"shiftCode\": \"SHF-MIDNIGHT-001\",\n  \"shiftName\": \"MidNight Shift - Standard\",\n  \"shiftType\": \"FIXED\",\n  \"applicabilityType\": \"DEFAULT\",\n  \"startTime\": \"09:00:00\",\n  \"endTime\": \"18:00:00\",\n  \"graceMinutes\": 15,\n  \"requiredDurationHours\": null,\n  \"effectiveFrom\": \"01-Aug-2026\",\n  \"effectiveTo\": \"31-Dec-2026\",\n  \"isDeleted\": \"N\",\n  \"description\": \"xyz\",\n  \"remarks\": \"Standard morning shift for all employees\",\n  \"breakConfigs\": [\n    {\n      \"breakName\": \"Lunch Break\",\n      \"breakDurationMinutes\": 60,\n      \"paidFlag\": false\n    },\n    {\n      \"breakName\": \"Tea Break\",\n      \"breakDurationMinutes\": 15,\n      \"paidFlag\": true\n    },\n    {\n      \"breakName\": \"Evening Tea\",\n      \"breakDurationMinutes\": 15,\n      \"paidFlag\": true\n    }\n  ],\n  \"applicableEmpIds\": null\n}",
  "Request Body Schema": "{\"shiftCode\":\"string\",\"shiftName\":\"string\",\"shiftType\":\"string\",\"applicabilityType\":\"string\",\"startTime\":\"string\",\"endTime\":\"string\",\"graceMinutes\":\"number\",\"requiredDurationHours\":\"null\",\"effectiveFrom\":\"string\",\"effectiveTo\":\"string\",\"isDeleted\":\"string\",\"description\":\"string\",\"remarks\":\"string\",\"breakConfigs\":[{\"breakName\":\"string\",\"breakDurationMinutes\":\"number\",\"paidFlag\":\"boolean\"}],\"applicableEmpIds\":\"null\"}",
  "Response (example/200)": "",
  "Example Response Payload": "",
  "Dependent APIs / Services": "Requires authToken from Employee Auth API; Depends on Employee Auth API POST /auth/token for authToken",
  "Owner / Developer": "",
  "API Identifier": "post|{{baseurl}}|/api/v1/attendance/shift/master|attendance shift master|create new shift",
  "Comments": "Source: collections/Attendance_Management_API.json; No saved response example in source file"
}""")

@allure.title("Create New Shift \u2014 returns HTTP 200")
@allure.epic("Attendance Shift Master")
@allure.feature("POST /api/v1/attendance/shift/master — Create New Shift")
@allure.story("HTTP Status Code Check (200)")
@allure.parent_suite("Attendance Shift Master")
@allure.suite("POST /api/v1/attendance/shift/master — Create New Shift")
@allure.sub_suite("HTTP Status Code Check (200)")
@allure.label("sourceModule", "Attendance Shift Master")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("post|{{baseurl}}|/api/v1/attendance/shift/master|attendance shift master|create new shift", name="API Identifier")
def test_attendance_shift_master_api_v1_attendance_shift_master_status_code(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "POST")
    allure.dynamic.parameter("Endpoint Path", "/api/v1/attendance/shift/master")
    allure.dynamic.parameter("Expected Status", "200")
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


@allure.title("Create New Shift \u2014 response matches documented schema")
@allure.epic("Attendance Shift Master")
@allure.feature("POST /api/v1/attendance/shift/master — Create New Shift")
@allure.story("OpenAPI Schema Validation Check")
@allure.parent_suite("Attendance Shift Master")
@allure.suite("POST /api/v1/attendance/shift/master — Create New Shift")
@allure.sub_suite("OpenAPI Schema Validation Check")
@allure.label("sourceModule", "Attendance Shift Master")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("post|{{baseurl}}|/api/v1/attendance/shift/master|attendance shift master|create new shift", name="API Identifier")
def test_attendance_shift_master_api_v1_attendance_shift_master_response_schema(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "POST")
    allure.dynamic.parameter("Endpoint Path", "/api/v1/attendance/shift/master")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
