"""Generated tests for API row 2.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "2",
  "Module Name": "Employee Auth API",
  "Sub-Module Name": "TC01 - Valid credentials return JWT token",
  "Access": "public",
  "Functional Purpose": "TC01 - Status is 200; TC01 - Full response matches OpenAPI LoginResponse; TC01 - Token is three-part JWT; TC01 - empCode and username returned; TC01 - roles is non-empty array",
  "Base URL": "{{authBaseUrl}}",
  "Endpoint / Path": "/auth/token",
  "HTTP Method": "POST",
  "Request Parameters": "headers: Content-Type=application/json",
  "Request Body": "{\"empCode\": \"{{empCode}}\", \"password\": \"{{empPassword}}\"}",
  "Example Request Payload": "{\n  \"empCode\": \"<empCode>\",\n  \"password\": \"<empPassword>\"\n}",
  "Request Body Schema": "{\"empCode\":\"string\",\"password\":\"string\"}",
  "Response (example/200)": "Expected status(es): 200\n{\n  \"empCode\": \"<empCode>\",\n  \"roles\": [\n    \"<role>\"\n  ],\n  \"token\": \"<jwt-token>\",\n  \"username\": \"<username>\"\n}",
  "Example Response Payload": "{\n  \"empCode\": \"<empCode>\",\n  \"roles\": [\n    \"<role>\"\n  ],\n  \"token\": \"<jwt-token>\",\n  \"username\": \"<username>\"\n}",
  "Dependent APIs / Services": "Produces authToken for downstream APIs",
  "Owner / Developer": "Parth Divekar <parthdivekar987@gmail.com>",
  "API Identifier": "post|/auth/token|employee auth api|tc01 - valid credentials return jwt token",
  "Comments": "Source: collections/auth/Employee_Auth_API.json; No saved response example in source file"
}""")

@allure.title("TC01 - Valid credentials return JWT token \u2014 returns HTTP 200")
@allure.epic("Employee Auth API")
@allure.feature("POST /auth/token — TC01 - Valid credentials return JWT token")
@allure.story("HTTP Status Code Check (200)")
@allure.parent_suite("Employee Auth API")
@allure.suite("POST /auth/token — TC01 - Valid credentials return JWT token")
@allure.sub_suite("HTTP Status Code Check (200)")
@allure.label("sourceModule", "Employee Auth API")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "Parth Divekar <parthdivekar987@gmail.com>")
@allure.link("post|/auth/token|employee auth api|tc01 - valid credentials return jwt token", name="API Identifier")
def test_employee_auth_api_auth_token_status_code(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "POST")
    allure.dynamic.parameter("Endpoint Path", "/auth/token")
    allure.dynamic.parameter("Expected Status", "200")
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


@allure.title("TC01 - Valid credentials return JWT token \u2014 response matches documented schema")
@allure.epic("Employee Auth API")
@allure.feature("POST /auth/token — TC01 - Valid credentials return JWT token")
@allure.story("OpenAPI Schema Validation Check")
@allure.parent_suite("Employee Auth API")
@allure.suite("POST /auth/token — TC01 - Valid credentials return JWT token")
@allure.sub_suite("OpenAPI Schema Validation Check")
@allure.label("sourceModule", "Employee Auth API")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "Parth Divekar <parthdivekar987@gmail.com>")
@allure.link("post|/auth/token|employee auth api|tc01 - valid credentials return jwt token", name="API Identifier")
def test_employee_auth_api_auth_token_response_schema(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "POST")
    allure.dynamic.parameter("Endpoint Path", "/auth/token")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
