"""Generated tests for API row 1.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "1",
  "Module Name": "auth",
  "Sub-Module Name": "Login",
  "Access": "public",
  "Functional Purpose": "Status is 200; Token exists; empCode matches",
  "Base URL": "{{baseUrl}}",
  "Endpoint / Path": "/auth/token",
  "HTTP Method": "POST",
  "Request Parameters": "",
  "Request Body": "{\n    \"empCode\": \"{{empCode}}\",\n    \"password\": \"{{empPassword}}\"\n  }",
  "Example Request Payload": "{\n  \"empCode\": \"<empCode>\",\n  \"password\": \"<empPassword>\"\n}",
  "Request Body Schema": "{\"empCode\":\"string\",\"password\":\"string\"}",
  "Response (example/200)": "Expected status(es): 200\n{\n  \"token\": \"<jwt-token>\"\n}",
  "Example Response Payload": "{\n  \"token\": \"<jwt-token>\"\n}",
  "Dependent APIs / Services": "Produces authToken for downstream APIs",
  "Owner / Developer": "",
  "API Identifier": "post|/auth/token|auth|login",
  "Comments": "Source: bruno/auth/login.bru; No saved response example in source file; Parsed from Bruno file"
}""")

@allure.title("Login - Status is 200; Token exists; empCode matches \u2014 returns HTTP 200")
@allure.epic("auth")
@allure.feature("POST /auth/token — Login")
@allure.story("HTTP Status Code Check (200)")
@allure.parent_suite("auth")
@allure.suite("POST /auth/token — Login")
@allure.sub_suite("HTTP Status Code Check (200)")
@allure.label("sourceModule", "auth")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("post|/auth/token|auth|login", name="API Identifier")
def test_auth_auth_token_status_code(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "POST")
    allure.dynamic.parameter("Endpoint Path", "/auth/token")
    allure.dynamic.parameter("Expected Status", "200")
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


@allure.title("Login - Status is 200; Token exists; empCode matches \u2014 response matches documented schema")
@allure.epic("auth")
@allure.feature("POST /auth/token — Login")
@allure.story("OpenAPI Schema Validation Check")
@allure.parent_suite("auth")
@allure.suite("POST /auth/token — Login")
@allure.sub_suite("OpenAPI Schema Validation Check")
@allure.label("sourceModule", "auth")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("post|/auth/token|auth|login", name="API Identifier")
def test_auth_auth_token_response_schema(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "POST")
    allure.dynamic.parameter("Endpoint Path", "/auth/token")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
