"""Generated tests for API row 3.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "3",
  "Module Name": "Employee Auth API",
  "Sub-Module Name": "TC02 - Invalid empCode returns 400",
  "Access": "public",
  "Functional Purpose": "TC02 - Status is 400 for bad empCode; TC02 - Error message returned",
  "Base URL": "{{authBaseUrl}}",
  "Endpoint / Path": "/auth/token",
  "HTTP Method": "POST",
  "Request Parameters": "headers: Content-Type=application/json",
  "Request Body": "{\"empCode\": \"INVALID-999\", \"password\": \"wrongpassword\"}",
  "Example Request Payload": "{\n  \"empCode\": \"INVALID-999\",\n  \"password\": \"wrongpassword\"\n}",
  "Request Body Schema": "{\"empCode\":\"string\",\"password\":\"string\"}",
  "Response (example/200)": "Expected status(es): 400\n{\n  \"token\": \"<jwt-token>\"\n}",
  "Example Response Payload": "{\n  \"token\": \"<jwt-token>\"\n}",
  "Dependent APIs / Services": "",
  "Owner / Developer": "KavishTadas <kavish.tadas@omfysgroup.com>",
  "API Identifier": "post|{{authbaseurl}}|/auth/token|employee auth api|tc02 - invalid empcode returns 400",
  "Comments": "Source: collections/Employee_Auth_API.json; No saved response example in source file"
}""")

@allure.epic("Employee Auth API")
@allure.feature("Employee Auth API APIs")
@allure.story("POST /auth/token")
@pytest.mark.skip(reason="Temporarily disabled per user request due to negative scenario mismatch")
def test_employee_auth_api_auth_token_status_code(api_runtime_config: dict[str, str]) -> None:
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 400


@allure.epic("Employee Auth API")
@allure.feature("Employee Auth API APIs")
@allure.story("POST /auth/token")
def test_employee_auth_api_auth_token_response_schema(api_runtime_config: dict[str, str]) -> None:
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 400
    assert_response_matches_schema(response, API)
