"""Generated tests for API row 42.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "42",
  "Module Name": "Attenedance-july2026",
  "Sub-Module Name": "week-off-assignment/getByWeekOffId",
  "Access": "private",
  "Functional Purpose": "week-off-assignment/getByWeekOffId",
  "Base URL": "https://devmcdphcmplatform.omfysgroup.com",
  "Endpoint / Path": "/api/attendance/week-off-assignment/getByWeekOff",
  "HTTP Method": "POST",
  "Request Parameters": "query: page=0; size=10; sort=employeeId,asc | headers: Authorization=Bearer <YOUR_JWT_TOKEN>; Content-Type=application/json",
  "Request Body": "{\n    \"weekOffId\": 1\n}",
  "Example Request Payload": "{\n  \"weekOffId\": 1\n}",
  "Request Body Schema": "{\"weekOffId\":\"number\"}",
  "Response (example/200)": "",
  "Example Response Payload": "",
  "Dependent APIs / Services": "",
  "Owner / Developer": "",
  "API Identifier": "post|/api/attendance/week-off-assignment/getbyweekoff|attenedance-july2026|week-off-assignment/getbyweekoffid",
  "Comments": "Source: collections/Weekoff_Policy_API.json; No saved response example in source file"
}""")

@allure.title("Week off assignment - Get by Week Off ID \u2014 returns HTTP 200")
@allure.epic("Attenedance-july2026")
@allure.feature("POST /api/attendance/week-off-assignment/getByWeekOff — week-off-assignment/getByWeekOffId")
@allure.story("HTTP Status Code Check (200)")
@allure.parent_suite("Attenedance-july2026")
@allure.suite("POST /api/attendance/week-off-assignment/getByWeekOff — week-off-assignment/getByWeekOffId")
@allure.sub_suite("HTTP Status Code Check (200)")
@allure.label("sourceModule", "Attenedance-july2026")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("post|/api/attendance/week-off-assignment/getbyweekoff|attenedance-july2026|week-off-assignment/getbyweekoffid", name="API Identifier")
def test_attenedance_july2026_api_attendance_week_off_assignment_getbyweekoff_status_code(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "POST")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/week-off-assignment/getByWeekOff")
    allure.dynamic.parameter("Expected Status", "200")
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


@allure.title("Week off assignment - Get by Week Off ID \u2014 response matches documented schema")
@allure.epic("Attenedance-july2026")
@allure.feature("POST /api/attendance/week-off-assignment/getByWeekOff — week-off-assignment/getByWeekOffId")
@allure.story("OpenAPI Schema Validation Check")
@allure.parent_suite("Attenedance-july2026")
@allure.suite("POST /api/attendance/week-off-assignment/getByWeekOff — week-off-assignment/getByWeekOffId")
@allure.sub_suite("OpenAPI Schema Validation Check")
@allure.label("sourceModule", "Attenedance-july2026")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("post|/api/attendance/week-off-assignment/getbyweekoff|attenedance-july2026|week-off-assignment/getbyweekoffid", name="API Identifier")
def test_attenedance_july2026_api_attendance_week_off_assignment_getbyweekoff_response_schema(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "POST")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/week-off-assignment/getByWeekOff")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
