"""Generated tests for API row 7.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "7",
  "Module Name": "users",
  "Sub-Module Name": "Get profile",
  "Access": "private",
  "Functional Purpose": "Status is 200; Email is a string",
  "Base URL": "{{BASE_URL}}",
  "Endpoint / Path": "/users/me",
  "HTTP Method": "GET",
  "Request Parameters": "auth: bearer token={{authToken}}",
  "Request Body": "",
  "Example Request Payload": "",
  "Request Body Schema": "",
  "Response (example/200)": "Expected status(es): 200\n{\n  \"email\": \"<email>\"\n}",
  "Example Response Payload": "{\n  \"email\": \"<email>\"\n}",
  "Dependent APIs / Services": "Requires authToken from Login API; Depends on Login API POST /auth/token for authToken",
  "Owner / Developer": "KavishTadas <kavish.tadas@omfysgroup.com>",
  "API Identifier": "get|{{base_url}}|/users/me|users|get profile",
  "Comments": "Source: bruno/users/get-profile.bru; No saved response example in source file; Parsed from Bruno file"
}""")

def test_users_users_me_status_code(api_runtime_config: dict[str, str]) -> None:
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


def test_users_users_me_response_schema(api_runtime_config: dict[str, str]) -> None:
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
