"""Generated tests for API row 8.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "8",
  "Module Name": "Employee Auth API",
  "Sub-Module Name": "TC01 - Valid credentials return JWT token",
  "Access": "public",
  "Functional Purpose": "TC01 - Status is 200; TC01 - Token is three-part JWT; TC01 - empCode and username returned; TC01 - roles is non-empty array",
  "Base URL": "{{baseUrl}}",
  "Endpoint / Path": "/auth/token",
  "HTTP Method": "POST",
  "Request Parameters": "headers: Content-Type=application/json",
  "Request Body": "{\"empCode\": \"{{empCode}}\", \"password\": \"{{empPassword}}\"}",
  "Example Request Payload": "{\n  \"empCode\": \"<empCode>\",\n  \"password\": \"<empPassword>\"\n}",
  "Request Body Schema": "{\"empCode\":\"string\",\"password\":\"string\"}",
  "Response (example/200)": "Expected status(es): 200\n{\n  \"empCode\": \"<empCode>\",\n  \"roles\": [\n    \"<role>\"\n  ],\n  \"token\": \"<jwt-token>\",\n  \"username\": \"<username>\"\n}",
  "Example Response Payload": "{\n  \"empCode\": \"<empCode>\",\n  \"roles\": [\n    \"<role>\"\n  ],\n  \"token\": \"<jwt-token>\",\n  \"username\": \"<username>\"\n}",
  "Dependent APIs / Services": "Produces authToken for downstream APIs",
  "Owner / Developer": "",
  "API Identifier": "post|{{baseurl}}|/auth/token|employee auth api|tc01 - valid credentials return jwt token",
  "Comments": "Source: collections/Employee_Auth_API.json; No saved response example in source file"
}""")

def test_employee_auth_api_auth_token_status_code(api_runtime_config: dict[str, str]) -> None:
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


def test_employee_auth_api_auth_token_response_schema(api_runtime_config: dict[str, str]) -> None:
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
