"""Generated tests for API row 31.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "31",
  "Module Name": "Latearly-Policy",
  "Sub-Module Name": "getById/1",
  "Access": "private",
  "Functional Purpose": "Generated from cURL: curl --location 'http://localhost:9079/api/attendance/late-early-policies/getById/1' \\\n--header 'Authorization: Bearer <JWT_TOKEN>'",
  "Base URL": "{{baseURL}}",
  "Endpoint / Path": "/api/attendance/late-early-policies/getById/5",
  "HTTP Method": "GET",
  "Request Parameters": "headers: Authorization=Bearer <JWT_TOKEN>",
  "Request Body": "",
  "Example Request Payload": "",
  "Request Body Schema": "",
  "Response (example/200)": "",
  "Example Response Payload": "",
  "Dependent APIs / Services": "",
  "Owner / Developer": "Parth Divekar <parthdivekar987@gmail.com>",
  "API Identifier": "get|/api/attendance/late-early-policies/getbyid/5|latearly-policy|getbyid/1",
  "Comments": "Source: collections/Late_Early_Policy_API.json; No saved response example in source file"
}""")

@allure.title("Get by ID \u2014 returns HTTP 200")
@allure.epic("Latearly-Policy")
@allure.feature("GET /api/attendance/late-early-policies/getById/5 — getById/1")
@allure.story("HTTP Status Code Check (200)")
@allure.parent_suite("Latearly-Policy")
@allure.suite("GET /api/attendance/late-early-policies/getById/5 — getById/1")
@allure.sub_suite("HTTP Status Code Check (200)")
@allure.label("sourceModule", "Latearly-Policy")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "Parth Divekar <parthdivekar987@gmail.com>")
@allure.link("get|/api/attendance/late-early-policies/getbyid/5|latearly-policy|getbyid/1", name="API Identifier")
def test_latearly_policy_api_attendance_late_early_policies_getbyid_5_status_code(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "GET")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/late-early-policies/getById/5")
    allure.dynamic.parameter("Expected Status", "200")
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


@allure.title("Get by ID \u2014 response matches documented schema")
@allure.epic("Latearly-Policy")
@allure.feature("GET /api/attendance/late-early-policies/getById/5 — getById/1")
@allure.story("OpenAPI Schema Validation Check")
@allure.parent_suite("Latearly-Policy")
@allure.suite("GET /api/attendance/late-early-policies/getById/5 — getById/1")
@allure.sub_suite("OpenAPI Schema Validation Check")
@allure.label("sourceModule", "Latearly-Policy")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "Parth Divekar <parthdivekar987@gmail.com>")
@allure.link("get|/api/attendance/late-early-policies/getbyid/5|latearly-policy|getbyid/1", name="API Identifier")
def test_latearly_policy_api_attendance_late_early_policies_getbyid_5_response_schema(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "GET")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/late-early-policies/getById/5")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
