"""Generated tests for API row 36.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "36",
  "Module Name": "Attenedance-july2026",
  "Sub-Module Name": "WeekOffGetAll",
  "Access": "private",
  "Functional Purpose": "WeekOffGetAll",
  "Base URL": "{{baseURL}}",
  "Endpoint / Path": "/api/attendance/week-offs/getAll",
  "HTTP Method": "GET",
  "Request Parameters": "query: page=0; size=10; sort=weekOffName,asc | headers: Authorization=Bearer YOUR_JWT_TOKEN",
  "Request Body": "",
  "Example Request Payload": "",
  "Request Body Schema": "",
  "Response (example/200)": "",
  "Example Response Payload": "",
  "Dependent APIs / Services": "",
  "Owner / Developer": "Parth Divekar <parthdivekar987@gmail.com>",
  "API Identifier": "get|/api/attendance/week-offs/getall|attenedance-july2026|weekoffgetall",
  "Comments": "Source: collections/Weekoff_Policy_API.json; No saved response example in source file"
}""")

@allure.title("Week Off Get All \u2014 returns HTTP 200")
@allure.epic("Attenedance-july2026")
@allure.feature("GET /api/attendance/week-offs/getAll — WeekOffGetAll")
@allure.story("HTTP Status Code Check (200)")
@allure.parent_suite("Attenedance-july2026")
@allure.suite("GET /api/attendance/week-offs/getAll — WeekOffGetAll")
@allure.sub_suite("HTTP Status Code Check (200)")
@allure.label("sourceModule", "Attenedance-july2026")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "Parth Divekar <parthdivekar987@gmail.com>")
@allure.link("get|/api/attendance/week-offs/getall|attenedance-july2026|weekoffgetall", name="API Identifier")
def test_attenedance_july2026_api_attendance_week_offs_getall_status_code(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "GET")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/week-offs/getAll")
    allure.dynamic.parameter("Expected Status", "200")
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


@allure.title("Week Off Get All \u2014 response matches documented schema")
@allure.epic("Attenedance-july2026")
@allure.feature("GET /api/attendance/week-offs/getAll — WeekOffGetAll")
@allure.story("OpenAPI Schema Validation Check")
@allure.parent_suite("Attenedance-july2026")
@allure.suite("GET /api/attendance/week-offs/getAll — WeekOffGetAll")
@allure.sub_suite("OpenAPI Schema Validation Check")
@allure.label("sourceModule", "Attenedance-july2026")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "Parth Divekar <parthdivekar987@gmail.com>")
@allure.link("get|/api/attendance/week-offs/getall|attenedance-july2026|weekoffgetall", name="API Identifier")
def test_attenedance_july2026_api_attendance_week_offs_getall_response_schema(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "GET")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/week-offs/getAll")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
