"""Generated tests for API row 45.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "45",
  "Module Name": "users",
  "Sub-Module Name": "Get profile",
  "Access": "private",
  "Functional Purpose": "Status is 200; Email is a string",
  "Base URL": "{{BASE_URL}}",
  "Endpoint / Path": "/users/me",
  "HTTP Method": "GET",
  "Request Parameters": "auth: bearer token={{authToken}}",
  "Request Body": "",
  "Example Request Payload": "",
  "Request Body Schema": "",
  "Response (example/200)": "Expected status(es): 200\n{\n  \"email\": \"<email>\"\n}",
  "Example Response Payload": "{\n  \"email\": \"<email>\"\n}",
  "Dependent APIs / Services": "Requires authToken from Employee Auth API; Depends on Employee Auth API POST /auth/token for authToken",
  "Owner / Developer": "",
  "API Identifier": "get|/users/me|users|get profile",
  "Comments": "Source: bruno/users/get-profile.bru; No saved response example in source file; Parsed from Bruno file"
}""")

@allure.title("Get profile - Status is 200; Email is a string \u2014 returns HTTP 200")
@allure.epic("users")
@allure.feature("GET /users/me — Get profile")
@allure.story("HTTP Status Code Check (200)")
@allure.parent_suite("users")
@allure.suite("GET /users/me — Get profile")
@allure.sub_suite("HTTP Status Code Check (200)")
@allure.label("sourceModule", "users")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("get|/users/me|users|get profile", name="API Identifier")
def test_users_users_me_status_code(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "GET")
    allure.dynamic.parameter("Endpoint Path", "/users/me")
    allure.dynamic.parameter("Expected Status", "200")
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


@allure.title("Get profile - Status is 200; Email is a string \u2014 response matches documented schema")
@allure.epic("users")
@allure.feature("GET /users/me — Get profile")
@allure.story("OpenAPI Schema Validation Check")
@allure.parent_suite("users")
@allure.suite("GET /users/me — Get profile")
@allure.sub_suite("OpenAPI Schema Validation Check")
@allure.label("sourceModule", "users")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("get|/users/me|users|get profile", name="API Identifier")
def test_users_users_me_response_schema(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "GET")
    allure.dynamic.parameter("Endpoint Path", "/users/me")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
