"""Generated tests for API row 4.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "4",
  "Module Name": "Leave API",
  "Sub-Module Name": "TC04 - Pending approvals rejects missing auth",
  "Access": "private",
  "Functional Purpose": "TC04 - Status is 401 or 403 without token",
  "Base URL": "{{leaveBaseUrl}}",
  "Endpoint / Path": "/user/leaves/approvals",
  "HTTP Method": "GET",
  "Request Parameters": "",
  "Request Body": "",
  "Example Request Payload": "",
  "Request Body Schema": "",
  "Response (example/200)": "Expected status(es): 401, 403",
  "Example Response Payload": "",
  "Dependent APIs / Services": "",
  "Owner / Developer": "KavishTadas <kavish.tadas@omfysgroup.com>",
  "API Identifier": "get|{{leavebaseurl}}|/user/leaves/approvals|leave api|tc04 - pending approvals rejects missing auth",
  "Comments": "Source: collections/Leave_API.json; Data-driven: test-data/Leave_API.csv; No saved response example in source file"
}""")

pytestmark = pytest.mark.skip(reason="API row documents a non-200 or negative scenario, not a valid request")

def test_leave_api_user_leaves_approvals_status_code(api_runtime_config: dict[str, str]) -> None:
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


def test_leave_api_user_leaves_approvals_response_schema(api_runtime_config: dict[str, str]) -> None:
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
