"""Generated tests for API row 26.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "26",
  "Module Name": "Holiday Template APIs Copy",
  "Sub-Module Name": "Create",
  "Access": "private",
  "Functional Purpose": "Create",
  "Base URL": "{{baseURL}}",
  "Endpoint / Path": "/api/attendance/holiday-templates/create",
  "HTTP Method": "POST",
  "Request Parameters": "headers: Authorization=Bearer {{jwtToken}}; Content-Type=application/json",
  "Request Body": "{\n  \"templateCode\": \"HOL2026\",\n  \"templateName\": \"India Holiday Calendar 2026\",\n  \"description\": \"National Holidays\",\n  \"effectiveFrom\": \"2026-01-01\",\n  \"effectiveTo\": \"2026-12-31\",\n  \"optionModel\": \"ALLOWED\",\n  \"templateMode\": \"DEFAULT\",\n  \"isDefault\": \"Y\",\n  \"isActive\": \"Y\",\n  \"templateStatus\": \"DRAFT\",\n  \"remarks\": \"2026\",\n  \"holidays\": [\n    {\n      \"holidayName\": \"Republic Day\",\n      \"occasion\": \"National Holiday\",\n      \"holidayDate\": \"2026-01-26\",\n      \"isOptional\": \"N\",\n      \"isHalfDay\": \"N\",\n      \"remarks\": \"\"\n    }\n  ],\n  \"assignments\": [\n    {\n      \"employeeId\": 101,\n      \"effectiveFrom\": \"2026-01-01\",\n      \"effectiveTo\": \"2026-12-31\",\n      \"isActive\": \"Y\"\n    }\n  ]\n}",
  "Example Request Payload": "{\n  \"templateCode\": \"HOL2026\",\n  \"templateName\": \"India Holiday Calendar 2026\",\n  \"description\": \"National Holidays\",\n  \"effectiveFrom\": \"2026-01-01\",\n  \"effectiveTo\": \"2026-12-31\",\n  \"optionModel\": \"ALLOWED\",\n  \"templateMode\": \"DEFAULT\",\n  \"isDefault\": \"Y\",\n  \"isActive\": \"Y\",\n  \"templateStatus\": \"DRAFT\",\n  \"remarks\": \"2026\",\n  \"holidays\": [\n    {\n      \"holidayName\": \"Republic Day\",\n      \"occasion\": \"National Holiday\",\n      \"holidayDate\": \"2026-01-26\",\n      \"isOptional\": \"N\",\n      \"isHalfDay\": \"N\",\n      \"remarks\": \"\"\n    }\n  ],\n  \"assignments\": [\n    {\n      \"employeeId\": 101,\n      \"effectiveFrom\": \"2026-01-01\",\n      \"effectiveTo\": \"2026-12-31\",\n      \"isActive\": \"Y\"\n    }\n  ]\n}",
  "Request Body Schema": "{\"templateCode\":\"string\",\"templateName\":\"string\",\"description\":\"string\",\"effectiveFrom\":\"string\",\"effectiveTo\":\"string\",\"optionModel\":\"string\",\"templateMode\":\"string\",\"isDefault\":\"string\",\"isActive\":\"string\",\"templateStatus\":\"string\",\"remarks\":\"string\",\"holidays\":[{\"holidayName\":\"string\",\"occasion\":\"string\",\"holidayDate\":\"string\",\"isOptional\":\"string\",\"isHalfDay\":\"string\",\"remarks\":\"string\"}],\"assignments\":[{\"employeeId\":\"number\",\"effectiveFrom\":\"string\",\"effectiveTo\":\"string\",\"isActive\":\"string\"}]}",
  "Response (example/200)": "",
  "Example Response Payload": "",
  "Dependent APIs / Services": "",
  "Owner / Developer": "Parth Divekar <parthdivekar987@gmail.com>",
  "API Identifier": "post|/api/attendance/holiday-templates/create|holiday template apis copy|create",
  "Comments": "Source: collections/Holiday_Template_API.json; No saved response example in source file"
}""")

@allure.title("Create \u2014 returns HTTP 200")
@allure.epic("Holiday Template APIs Copy")
@allure.feature("POST /api/attendance/holiday-templates/create — Create")
@allure.story("HTTP Status Code Check (200)")
@allure.parent_suite("Holiday Template APIs Copy")
@allure.suite("POST /api/attendance/holiday-templates/create — Create")
@allure.sub_suite("HTTP Status Code Check (200)")
@allure.label("sourceModule", "Holiday Template APIs Copy")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "Parth Divekar <parthdivekar987@gmail.com>")
@allure.link("post|/api/attendance/holiday-templates/create|holiday template apis copy|create", name="API Identifier")
def test_holiday_template_apis_copy_api_attendance_holiday_templates_create_status_code(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "POST")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/holiday-templates/create")
    allure.dynamic.parameter("Expected Status", "200")
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


@allure.title("Create \u2014 response matches documented schema")
@allure.epic("Holiday Template APIs Copy")
@allure.feature("POST /api/attendance/holiday-templates/create — Create")
@allure.story("OpenAPI Schema Validation Check")
@allure.parent_suite("Holiday Template APIs Copy")
@allure.suite("POST /api/attendance/holiday-templates/create — Create")
@allure.sub_suite("OpenAPI Schema Validation Check")
@allure.label("sourceModule", "Holiday Template APIs Copy")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "Parth Divekar <parthdivekar987@gmail.com>")
@allure.link("post|/api/attendance/holiday-templates/create|holiday template apis copy|create", name="API Identifier")
def test_holiday_template_apis_copy_api_attendance_holiday_templates_create_response_schema(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "POST")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/holiday-templates/create")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
