"""Generated tests for API row 20.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "20",
  "Module Name": "Attendance Status Threshold API",
  "Sub-Module Name": "Create Threshold",
  "Access": "private",
  "Functional Purpose": "Create Threshold",
  "Base URL": "{{baseUrl}}",
  "Endpoint / Path": "/api/attendance/status-threshold/create",
  "HTTP Method": "POST",
  "Request Parameters": "headers: Authorization=Bearer {{token}}; Content-Type=application/json",
  "Request Body": "{\n  \"thresholdCode\": \"CUST_STD_0001\",\n  \"thresholdName\": \"Standard Custom Thresholdsl\",\n  \"description\": \"Custom threshold for flexible shift employees\",\n  \"templateMode\": \"CUSTOM\",\n  \"shiftTypeApplicability\": \"ALL\",\n  \"absentMaxHours\": 3.00,\n  \"halfDayMinHours\": 3.01,\n  \"fullDayMinHours\": 5.00,\n  \"presentMinHours\": 8.00,\n  \"effectiveFrom\": \"2026-08-01\",\n  \"effectiveTo\": \"2026-12-31\",\n  \"isDefault\": \"N\",\n  \"isActive\": \"Y\",\n  \"templateStatus\": \"PUBLISHED\",\n  \"remarks\": \"Applicable for flexible shift employees only\",\n  \"assignments\": [\n    {\n      \"employeeId\": 41,\n      \"departmentId\": 1,\n      \"designationId\": 5,\n      \"isActive\": \"N\",\n      \"effectiveFrom\": \"2026-08-01\",\n      \"effectiveTo\": \"2026-12-31\"\n    },\n    {\n      \"employeeId\": 550,\n      \"departmentId\": 1,\n      \"designationId\": 6,\n      \"isActive\": \"Y\",\n      \"effectiveFrom\": \"2026-08-01\",\n      \"effectiveTo\": \"2026-08-01\"\n    }\n  ]\n}",
  "Example Request Payload": "{\n  \"thresholdCode\": \"CUST_STD_0001\",\n  \"thresholdName\": \"Standard Custom Thresholdsl\",\n  \"description\": \"Custom threshold for flexible shift employees\",\n  \"templateMode\": \"CUSTOM\",\n  \"shiftTypeApplicability\": \"ALL\",\n  \"absentMaxHours\": 3,\n  \"halfDayMinHours\": 3.01,\n  \"fullDayMinHours\": 5,\n  \"presentMinHours\": 8,\n  \"effectiveFrom\": \"2026-08-01\",\n  \"effectiveTo\": \"2026-12-31\",\n  \"isDefault\": \"N\",\n  \"isActive\": \"Y\",\n  \"templateStatus\": \"PUBLISHED\",\n  \"remarks\": \"Applicable for flexible shift employees only\",\n  \"assignments\": [\n    {\n      \"employeeId\": 41,\n      \"departmentId\": 1,\n      \"designationId\": 5,\n      \"isActive\": \"N\",\n      \"effectiveFrom\": \"2026-08-01\",\n      \"effectiveTo\": \"2026-12-31\"\n    },\n    {\n      \"employeeId\": 550,\n      \"departmentId\": 1,\n      \"designationId\": 6,\n      \"isActive\": \"Y\",\n      \"effectiveFrom\": \"2026-08-01\",\n      \"effectiveTo\": \"2026-08-01\"\n    }\n  ]\n}",
  "Request Body Schema": "{\"thresholdCode\":\"string\",\"thresholdName\":\"string\",\"description\":\"string\",\"templateMode\":\"string\",\"shiftTypeApplicability\":\"string\",\"absentMaxHours\":\"number\",\"halfDayMinHours\":\"number\",\"fullDayMinHours\":\"number\",\"presentMinHours\":\"number\",\"effectiveFrom\":\"string\",\"effectiveTo\":\"string\",\"isDefault\":\"string\",\"isActive\":\"string\",\"templateStatus\":\"string\",\"remarks\":\"string\",\"assignments\":[{\"employeeId\":\"number\",\"departmentId\":\"number\",\"designationId\":\"number\",\"isActive\":\"string\",\"effectiveFrom\":\"string\",\"effectiveTo\":\"string\"}]}",
  "Response (example/200)": "",
  "Example Response Payload": "",
  "Dependent APIs / Services": "",
  "Owner / Developer": "Parth Divekar <parthdivekar987@gmail.com>",
  "API Identifier": "post|/api/attendance/status-threshold/create|attendance status threshold api|create threshold",
  "Comments": "Source: collections/Attendance_Threshold_API.json; No saved response example in source file"
}""")

@allure.title("Create Threshold \u2014 returns HTTP 200")
@allure.epic("Attendance Status Threshold API")
@allure.feature("POST /api/attendance/status-threshold/create — Create Threshold")
@allure.story("HTTP Status Code Check (200)")
@allure.parent_suite("Attendance Status Threshold API")
@allure.suite("POST /api/attendance/status-threshold/create — Create Threshold")
@allure.sub_suite("HTTP Status Code Check (200)")
@allure.label("sourceModule", "Attendance Status Threshold API")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "Parth Divekar <parthdivekar987@gmail.com>")
@allure.link("post|/api/attendance/status-threshold/create|attendance status threshold api|create threshold", name="API Identifier")
def test_attendance_status_threshold_api_api_attendance_status_threshold_create_status_code(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "POST")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/status-threshold/create")
    allure.dynamic.parameter("Expected Status", "200")
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


@allure.title("Create Threshold \u2014 response matches documented schema")
@allure.epic("Attendance Status Threshold API")
@allure.feature("POST /api/attendance/status-threshold/create — Create Threshold")
@allure.story("OpenAPI Schema Validation Check")
@allure.parent_suite("Attendance Status Threshold API")
@allure.suite("POST /api/attendance/status-threshold/create — Create Threshold")
@allure.sub_suite("OpenAPI Schema Validation Check")
@allure.label("sourceModule", "Attendance Status Threshold API")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "Parth Divekar <parthdivekar987@gmail.com>")
@allure.link("post|/api/attendance/status-threshold/create|attendance status threshold api|create threshold", name="API Identifier")
def test_attendance_status_threshold_api_api_attendance_status_threshold_create_response_schema(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "POST")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/status-threshold/create")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
