"""Generated tests for API row 17.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "17",
  "Module Name": "Attendance Shift Master",
  "Sub-Module Name": "Delete Shift",
  "Access": "private",
  "Functional Purpose": "Delete Shift",
  "Base URL": "{{baseURL}}",
  "Endpoint / Path": "/api/v1/attendance/shift/master/6",
  "HTTP Method": "DELETE",
  "Request Parameters": "headers: Authorization=Bearer {{authToken}}",
  "Request Body": "{\n  \"shiftCode\": \"SHF-NIGHT-0002\",\n  \"shiftName\": \"Night Shift -Techno Support Team\",\n  \"shiftType\": \"FIXED\",\n  \"applicabilityType\": \"DEFAULT\",\n  \"startTime\": \"22:00:00\",\n  \"endTime\": \"06:00:00\",\n  \"graceMinutes\": 10,\n  \"requiredDurationHours\": null,\n  \"effectiveFrom\": \"01-Aug-2026\",\n  \"effectiveTo\": \"31-Mar-2027\",\n  \"activeFlag\": true,\n  \"remarks\": \"Night shift for global support team (cross-midnight)\",\n  \"breakConfigs\": [\n    {\n      \"breakName\": \"Dinner Break\",\n      \"breakDurationMinutes\": 45,\n      \"paidFlag\": false\n    },\n    {\n      \"breakName\": \"Shortscut Break\",\n      \"breakDurationMinutes\": 15,\n      \"paidFlag\": true\n    },\n    {\n      \"breakName\": \"Refreshment Break\",\n      \"breakDurationMinutes\": 10,\n      \"paidFlag\": true\n    }\n  ],\n  \"applicableEmpIds\": [3496,3500]\n}",
  "Example Request Payload": "{\n  \"shiftCode\": \"SHF-NIGHT-0002\",\n  \"shiftName\": \"Night Shift -Techno Support Team\",\n  \"shiftType\": \"FIXED\",\n  \"applicabilityType\": \"DEFAULT\",\n  \"startTime\": \"22:00:00\",\n  \"endTime\": \"06:00:00\",\n  \"graceMinutes\": 10,\n  \"requiredDurationHours\": null,\n  \"effectiveFrom\": \"01-Aug-2026\",\n  \"effectiveTo\": \"31-Mar-2027\",\n  \"activeFlag\": true,\n  \"remarks\": \"Night shift for global support team (cross-midnight)\",\n  \"breakConfigs\": [\n    {\n      \"breakName\": \"Dinner Break\",\n      \"breakDurationMinutes\": 45,\n      \"paidFlag\": false\n    },\n    {\n      \"breakName\": \"Shortscut Break\",\n      \"breakDurationMinutes\": 15,\n      \"paidFlag\": true\n    },\n    {\n      \"breakName\": \"Refreshment Break\",\n      \"breakDurationMinutes\": 10,\n      \"paidFlag\": true\n    }\n  ],\n  \"applicableEmpIds\": [\n    3496,\n    3500\n  ]\n}",
  "Request Body Schema": "{\"shiftCode\":\"string\",\"shiftName\":\"string\",\"shiftType\":\"string\",\"applicabilityType\":\"string\",\"startTime\":\"string\",\"endTime\":\"string\",\"graceMinutes\":\"number\",\"requiredDurationHours\":\"null\",\"effectiveFrom\":\"string\",\"effectiveTo\":\"string\",\"activeFlag\":\"boolean\",\"remarks\":\"string\",\"breakConfigs\":[{\"breakName\":\"string\",\"breakDurationMinutes\":\"number\",\"paidFlag\":\"boolean\"}],\"applicableEmpIds\":[\"number\"]}",
  "Response (example/200)": "",
  "Example Response Payload": "",
  "Dependent APIs / Services": "Requires authToken from Employee Auth API; Depends on Employee Auth API POST /auth/token for authToken",
  "Owner / Developer": "",
  "API Identifier": "delete|/api/v1/attendance/shift/master/6|attendance shift master|delete shift",
  "Comments": "Source: collections/Attendance_Management_API.json; No saved response example in source file"
}""")

@allure.title("Delete Shift \u2014 returns HTTP 200")
@allure.epic("Attendance Shift Master")
@allure.feature("DELETE /api/v1/attendance/shift/master/6 — Delete Shift")
@allure.story("HTTP Status Code Check (200)")
@allure.parent_suite("Attendance Shift Master")
@allure.suite("DELETE /api/v1/attendance/shift/master/6 — Delete Shift")
@allure.sub_suite("HTTP Status Code Check (200)")
@allure.label("sourceModule", "Attendance Shift Master")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("delete|/api/v1/attendance/shift/master/6|attendance shift master|delete shift", name="API Identifier")
def test_attendance_shift_master_api_v1_attendance_shift_master_6_status_code(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "DELETE")
    allure.dynamic.parameter("Endpoint Path", "/api/v1/attendance/shift/master/6")
    allure.dynamic.parameter("Expected Status", "200")
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


@allure.title("Delete Shift \u2014 response matches documented schema")
@allure.epic("Attendance Shift Master")
@allure.feature("DELETE /api/v1/attendance/shift/master/6 — Delete Shift")
@allure.story("OpenAPI Schema Validation Check")
@allure.parent_suite("Attendance Shift Master")
@allure.suite("DELETE /api/v1/attendance/shift/master/6 — Delete Shift")
@allure.sub_suite("OpenAPI Schema Validation Check")
@allure.label("sourceModule", "Attendance Shift Master")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("delete|/api/v1/attendance/shift/master/6|attendance shift master|delete shift", name="API Identifier")
def test_attendance_shift_master_api_v1_attendance_shift_master_6_response_schema(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "DELETE")
    allure.dynamic.parameter("Endpoint Path", "/api/v1/attendance/shift/master/6")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
