"""Generated tests for API row 6.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "6",
  "Module Name": "Leave API",
  "Sub-Module Name": "TC02 - Invalid token returns observed authorization status",
  "Access": "private",
  "Functional Purpose": "TC02 - Invalid token returns observed HTTP 401; TC02 - Invalid token response has observed error structure",
  "Base URL": "{{leaveBaseUrl}}",
  "Endpoint / Path": "/user/leaves/getAllLeaveReports",
  "HTTP Method": "GET",
  "Request Parameters": "query: month=4; year=2026 | headers: Authorization=Bearer invalid-token-value",
  "Request Body": "",
  "Example Request Payload": "",
  "Request Body Schema": "",
  "Response (example/200)": "Expected status(es): 401\n{\n  \"token\": \"<jwt-token>\"\n}",
  "Example Response Payload": "{\n  \"token\": \"<jwt-token>\"\n}",
  "Dependent APIs / Services": "",
  "Owner / Developer": "KavishTadas <kavish.tadas@omfysgroup.com>",
  "API Identifier": "get|{{leavebaseurl}}|/user/leaves/getallleavereports|leave api|tc02 - invalid token returns observed authorization status",
  "Comments": "Source: collections/Leave_API.json; Data-driven: test-data/Leave_API.csv; No saved response example in source file"
}""")

@allure.epic("Leave API")
@allure.feature("Leave API APIs")
@allure.story("GET /user/leaves/getAllLeaveReports")
@pytest.mark.skip(reason="Temporarily disabled per user request due to negative scenario mismatch")
def test_leave_api_user_leaves_getallleavereports_status_code(api_runtime_config: dict[str, str]) -> None:
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 401


@allure.epic("Leave API")
@allure.feature("Leave API APIs")
@allure.story("GET /user/leaves/getAllLeaveReports")
@pytest.mark.skip(reason="Temporarily disabled per user request due to negative scenario mismatch")
def test_leave_api_user_leaves_getallleavereports_response_schema(api_runtime_config: dict[str, str]) -> None:
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 401
    assert_response_matches_schema(response, API)
