"""Generated tests for API row 30.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "30",
  "Module Name": "Latearly-Policy",
  "Sub-Module Name": "update",
  "Access": "private",
  "Functional Purpose": "Generated from cURL: curl --location --request PUT 'http://localhost:9079/api/attendance/late-early-policies/update/1' \\\n--header 'Authorization: Bearer <JWT_TOKEN>' \\\n--header 'Content-Type: application/json' \\\n--data '{\n    \"policyCode\": \"LEP001\",\n    \"policyName\": \"Updated Late/Early Policy\",\n    \"description\": \"Updated Policy\",\n    \"templateMode\": \"DEFAULT\",\n    \"templateStatus\": \"PUBLISHED\",\n    \"eventCountMinutes\": 20,\n    \"graceMinutes\": 5,\n    \"graceEvent\": 2,\n    \"allowedEvent\": 3,\n    \"deductionType\": \"LEAVE\",\n    \"leaveDeductDays\": 1,\n    \"leaveTypeId\": 1,\n    \"fineAmount\": null,\n    \"effectiveFrom\": \"2026-08-01\",\n    \"effectiveTo\": null,\n    \"isDefault\": \"N\",\n    \"remarks\": \"Updated Policy\",\n    \"deductionPriorities\": [\n        {\n            \"priorityOrder\": 1,\n            \"leaveTypeId\": 1,\n            \"isActive\": \"Y\"\n        }\n    ],\n    \"assignments\": [\n        {\n            \"employeeId\": 1001,\n            \"effectiveFrom\": \"2026-08-01\",\n            \"effectiveTo\": null,\n            \"isActive\": \"Y\"\n        }\n    ]\n}'",
  "Base URL": "{{baseURL}}",
  "Endpoint / Path": "/api/attendance/late-early-policies/update/2",
  "HTTP Method": "PUT",
  "Request Parameters": "headers: Authorization=Bearer <JWT_TOKEN>; Content-Type=application/json",
  "Request Body": "{\n    \"policyCode\": \"LEP001\",\n    \"policyName\": \"Updated Late/Early Policy\",\n    \"description\": \"Updated Policy\",\n    \"templateMode\": \"DEFAULT\",\n    \"templateStatus\": \"PUBLISHED\",\n    \"eventCountMinutes\": 5,\n    \"graceMinutes\": 20,\n    \"graceEvent\": 2,\n    \"allowedEvent\": 3,\n    \"deductionType\": \"LEAVE\",\n    \"leaveDeductDays\": 1,\n    \"leaveTypeId\": 1,\n    \"fineAmount\": null,\n    \"effectiveFrom\": \"2026-08-01\",\n    \"effectiveTo\": null,\n    \"isDefault\": \"N\",\n    \"remarks\": \"Updated Policy\",\n    \"deductionPriorities\": [\n        {\n            \"priorityOrder\": 3,\n            \"leaveTypeId\": 1,\n            \"isActive\": \"Y\"\n        }\n    ],\n    \"assignments\": [\n        {\n            \"employeeId\": 3844,\n            \"effectiveFrom\": \"2026-08-01\",\n            \"effectiveTo\": null,\n            \"isActive\": \"Y\"\n        }\n    ]\n}",
  "Example Request Payload": "{\n  \"policyCode\": \"LEP001\",\n  \"policyName\": \"Updated Late/Early Policy\",\n  \"description\": \"Updated Policy\",\n  \"templateMode\": \"DEFAULT\",\n  \"templateStatus\": \"PUBLISHED\",\n  \"eventCountMinutes\": 5,\n  \"graceMinutes\": 20,\n  \"graceEvent\": 2,\n  \"allowedEvent\": 3,\n  \"deductionType\": \"LEAVE\",\n  \"leaveDeductDays\": 1,\n  \"leaveTypeId\": 1,\n  \"fineAmount\": null,\n  \"effectiveFrom\": \"2026-08-01\",\n  \"effectiveTo\": null,\n  \"isDefault\": \"N\",\n  \"remarks\": \"Updated Policy\",\n  \"deductionPriorities\": [\n    {\n      \"priorityOrder\": 3,\n      \"leaveTypeId\": 1,\n      \"isActive\": \"Y\"\n    }\n  ],\n  \"assignments\": [\n    {\n      \"employeeId\": 3844,\n      \"effectiveFrom\": \"2026-08-01\",\n      \"effectiveTo\": null,\n      \"isActive\": \"Y\"\n    }\n  ]\n}",
  "Request Body Schema": "{\"policyCode\":\"string\",\"policyName\":\"string\",\"description\":\"string\",\"templateMode\":\"string\",\"templateStatus\":\"string\",\"eventCountMinutes\":\"number\",\"graceMinutes\":\"number\",\"graceEvent\":\"number\",\"allowedEvent\":\"number\",\"deductionType\":\"string\",\"leaveDeductDays\":\"number\",\"leaveTypeId\":\"number\",\"fineAmount\":\"null\",\"effectiveFrom\":\"string\",\"effectiveTo\":\"null\",\"isDefault\":\"string\",\"remarks\":\"string\",\"deductionPriorities\":[{\"priorityOrder\":\"number\",\"leaveTypeId\":\"number\",\"isActive\":\"string\"}],\"assignments\":[{\"employeeId\":\"number\",\"effectiveFrom\":\"string\",\"effectiveTo\":\"null\",\"isActive\":\"string\"}]}",
  "Response (example/200)": "",
  "Example Response Payload": "",
  "Dependent APIs / Services": "",
  "Owner / Developer": "Parth Divekar <parthdivekar987@gmail.com>",
  "API Identifier": "put|/api/attendance/late-early-policies/update/2|latearly-policy|update",
  "Comments": "Source: collections/Late_Early_Policy_API.json; No saved response example in source file"
}""")

@allure.title("Update \u2014 returns HTTP 200")
@allure.epic("Latearly-Policy")
@allure.feature("PUT /api/attendance/late-early-policies/update/2 — update")
@allure.story("HTTP Status Code Check (200)")
@allure.parent_suite("Latearly-Policy")
@allure.suite("PUT /api/attendance/late-early-policies/update/2 — update")
@allure.sub_suite("HTTP Status Code Check (200)")
@allure.label("sourceModule", "Latearly-Policy")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "Parth Divekar <parthdivekar987@gmail.com>")
@allure.link("put|/api/attendance/late-early-policies/update/2|latearly-policy|update", name="API Identifier")
def test_latearly_policy_api_attendance_late_early_policies_update_2_status_code(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "PUT")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/late-early-policies/update/2")
    allure.dynamic.parameter("Expected Status", "200")
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


@allure.title("Update \u2014 response matches documented schema")
@allure.epic("Latearly-Policy")
@allure.feature("PUT /api/attendance/late-early-policies/update/2 — update")
@allure.story("OpenAPI Schema Validation Check")
@allure.parent_suite("Latearly-Policy")
@allure.suite("PUT /api/attendance/late-early-policies/update/2 — update")
@allure.sub_suite("OpenAPI Schema Validation Check")
@allure.label("sourceModule", "Latearly-Policy")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "Parth Divekar <parthdivekar987@gmail.com>")
@allure.link("put|/api/attendance/late-early-policies/update/2|latearly-policy|update", name="API Identifier")
def test_latearly_policy_api_attendance_late_early_policies_update_2_response_schema(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "PUT")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/late-early-policies/update/2")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
