"""Generated tests for API row 4.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "4",
  "Module Name": "Employee Auth API",
  "Sub-Module Name": "TC03 - Missing password returns 400",
  "Access": "public",
  "Functional Purpose": "TC03 - Status is 400 for missing password; TC03 - Validation message returned",
  "Base URL": "{{authBaseUrl}}",
  "Endpoint / Path": "/auth/token",
  "HTTP Method": "POST",
  "Request Parameters": "headers: Content-Type=application/json",
  "Request Body": "{\"empCode\": \"{{empCode}}\"}",
  "Example Request Payload": "{\n  \"empCode\": \"<empCode>\"\n}",
  "Request Body Schema": "{\"empCode\":\"string\"}",
  "Response (example/200)": "Expected status(es): 400\n{\n  \"token\": \"<jwt-token>\"\n}",
  "Example Response Payload": "{\n  \"token\": \"<jwt-token>\"\n}",
  "Dependent APIs / Services": "",
  "Owner / Developer": "KavishTadas <kavish.tadas@omfysgroup.com>",
  "API Identifier": "post|{{authbaseurl}}|/auth/token|employee auth api|tc03 - missing password returns 400",
  "Comments": "Source: collections/Employee_Auth_API.json; No saved response example in source file"
}""")

@allure.epic("Employee Auth API")
@allure.feature("POST /auth/token — TC03 - Missing password returns 400")
@allure.story("HTTP Status Code Check (400)")
@allure.label("owner", "KavishTadas <kavish.tadas@omfysgroup.com>")
@allure.link("post|{{authbaseurl}}|/auth/token|employee auth api|tc03 - missing password returns 400", name="API Identifier")
@pytest.mark.skip(reason="Temporarily disabled per user request due to negative scenario mismatch")
def test_employee_auth_api_auth_token_status_code(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "POST")
    allure.dynamic.parameter("Endpoint Path", "/auth/token")
    allure.dynamic.parameter("Expected Status", "400")
    response = perform_api_request(API, api_runtime_config)
    allure.attach(
        json.dumps(dict(response.headers), indent=2),
        name="Response Headers",
        attachment_type=allure.attachment_type.JSON
    )
    allure.attach(
        response.text[:2000],
        name="Response Body Snippet",
        attachment_type=allure.attachment_type.TEXT
    )
    assert response.status_code == 400


@allure.epic("Employee Auth API")
@allure.feature("POST /auth/token — TC03 - Missing password returns 400")
@allure.story("OpenAPI Schema Validation Check")
@allure.label("owner", "KavishTadas <kavish.tadas@omfysgroup.com>")
@allure.link("post|{{authbaseurl}}|/auth/token|employee auth api|tc03 - missing password returns 400", name="API Identifier")
@pytest.mark.skip(reason="Temporarily disabled per user request due to negative scenario mismatch")
def test_employee_auth_api_auth_token_response_schema(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "POST")
    allure.dynamic.parameter("Endpoint Path", "/auth/token")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 400
    assert_response_matches_schema(response, API)
