"""Generated tests for API row 27.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "27",
  "Module Name": "Holiday Template APIs Copy",
  "Sub-Module Name": "Update",
  "Access": "private",
  "Functional Purpose": "Update",
  "Base URL": "http://localhost:9078",
  "Endpoint / Path": "/api/attendance/holiday-templates/update/%7BholidayTemplateId%7D",
  "HTTP Method": "PUT",
  "Request Parameters": "headers: Authorization=Bearer {{jwtToken}}; Content-Type=application/json",
  "Request Body": "{}",
  "Example Request Payload": "{}",
  "Request Body Schema": "{}",
  "Response (example/200)": "",
  "Example Response Payload": "",
  "Dependent APIs / Services": "",
  "Owner / Developer": "",
  "API Identifier": "put|/api/attendance/holiday-templates/update/%7bholidaytemplateid%7d|holiday template apis copy|update",
  "Comments": "Source: collections/Holiday_Template_API.json; No saved response example in source file"
}""")

@allure.title("Update \u2014 returns HTTP 200")
@allure.epic("Holiday Template APIs Copy")
@allure.feature("PUT /api/attendance/holiday-templates/update/%7BholidayTemplateId%7D — Update")
@allure.story("HTTP Status Code Check (200)")
@allure.parent_suite("Holiday Template APIs Copy")
@allure.suite("PUT /api/attendance/holiday-templates/update/%7BholidayTemplateId%7D — Update")
@allure.sub_suite("HTTP Status Code Check (200)")
@allure.label("sourceModule", "Holiday Template APIs Copy")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("put|/api/attendance/holiday-templates/update/%7bholidaytemplateid%7d|holiday template apis copy|update", name="API Identifier")
def test_holiday_template_apis_copy_api_attendance_holiday_templates_update_7bholidaytemplateid_7d_status_code(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "PUT")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/holiday-templates/update/%7BholidayTemplateId%7D")
    allure.dynamic.parameter("Expected Status", "200")
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


@allure.title("Update \u2014 response matches documented schema")
@allure.epic("Holiday Template APIs Copy")
@allure.feature("PUT /api/attendance/holiday-templates/update/%7BholidayTemplateId%7D — Update")
@allure.story("OpenAPI Schema Validation Check")
@allure.parent_suite("Holiday Template APIs Copy")
@allure.suite("PUT /api/attendance/holiday-templates/update/%7BholidayTemplateId%7D — Update")
@allure.sub_suite("OpenAPI Schema Validation Check")
@allure.label("sourceModule", "Holiday Template APIs Copy")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("put|/api/attendance/holiday-templates/update/%7bholidaytemplateid%7d|holiday template apis copy|update", name="API Identifier")
def test_holiday_template_apis_copy_api_attendance_holiday_templates_update_7bholidaytemplateid_7d_response_schema(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "PUT")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/holiday-templates/update/%7BholidayTemplateId%7D")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
