"""Generated tests for API row 40.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "40",
  "Module Name": "Attenedance-july2026",
  "Sub-Module Name": "WeekOffUpdate",
  "Access": "private",
  "Functional Purpose": "WeekOffUpdate",
  "Base URL": "https://devmcdphcmplatform.omfysgroup.com",
  "Endpoint / Path": "/api/attendance/week-offs/update/1",
  "HTTP Method": "PUT",
  "Request Parameters": "headers: Authorization=Bearer YOUR_JWT_TOKEN; Content-Type=application/json",
  "Request Body": "{\n    \"weekOffCode\": \"WO001\",\n    \"weekOffName\": \"Updated Sunday Week Off\",\n    \"description\": \"Updated Description\",\n    \"optionModel\": \"ALLOWED\",\n    \"isDefault\": \"N\",\n    \"isActive\": \"Y\",\n    \"details\": [\n        {\n            \"dayOfWeek\": \"SATURDAY\",\n            \"weekNo\": 2,\n            \"isWeekOff\": \"Y\"\n        },\n        {\n            \"dayOfWeek\": \"SUNDAY\",\n            \"weekNo\": 1,\n            \"isWeekOff\": \"Y\"\n        }\n    ],\n    \"assignments\": [\n        {\n            \"employeeId\": 101,\n            \"departmentId\": 10,\n            \"locationId\": 1,\n            \"effectiveFrom\": \"2026-08-01\",\n            \"effectiveTo\": \"2026-12-31\",\n            \"isActive\": \"Y\"\n        }\n    ]\n}",
  "Example Request Payload": "{\n  \"weekOffCode\": \"WO001\",\n  \"weekOffName\": \"Updated Sunday Week Off\",\n  \"description\": \"Updated Description\",\n  \"optionModel\": \"ALLOWED\",\n  \"isDefault\": \"N\",\n  \"isActive\": \"Y\",\n  \"details\": [\n    {\n      \"dayOfWeek\": \"SATURDAY\",\n      \"weekNo\": 2,\n      \"isWeekOff\": \"Y\"\n    },\n    {\n      \"dayOfWeek\": \"SUNDAY\",\n      \"weekNo\": 1,\n      \"isWeekOff\": \"Y\"\n    }\n  ],\n  \"assignments\": [\n    {\n      \"employeeId\": 101,\n      \"departmentId\": 10,\n      \"locationId\": 1,\n      \"effectiveFrom\": \"2026-08-01\",\n      \"effectiveTo\": \"2026-12-31\",\n      \"isActive\": \"Y\"\n    }\n  ]\n}",
  "Request Body Schema": "{\"weekOffCode\":\"string\",\"weekOffName\":\"string\",\"description\":\"string\",\"optionModel\":\"string\",\"isDefault\":\"string\",\"isActive\":\"string\",\"details\":[{\"dayOfWeek\":\"string\",\"weekNo\":\"number\",\"isWeekOff\":\"string\"}],\"assignments\":[{\"employeeId\":\"number\",\"departmentId\":\"number\",\"locationId\":\"number\",\"effectiveFrom\":\"string\",\"effectiveTo\":\"string\",\"isActive\":\"string\"}]}",
  "Response (example/200)": "",
  "Example Response Payload": "",
  "Dependent APIs / Services": "",
  "Owner / Developer": "",
  "API Identifier": "put|/api/attendance/week-offs/update/1|attenedance-july2026|weekoffupdate",
  "Comments": "Source: collections/Weekoff_Policy_API.json; No saved response example in source file"
}""")

@allure.title("Week Off Update \u2014 returns HTTP 200")
@allure.epic("Attenedance-july2026")
@allure.feature("PUT /api/attendance/week-offs/update/1 — WeekOffUpdate")
@allure.story("HTTP Status Code Check (200)")
@allure.parent_suite("Attenedance-july2026")
@allure.suite("PUT /api/attendance/week-offs/update/1 — WeekOffUpdate")
@allure.sub_suite("HTTP Status Code Check (200)")
@allure.label("sourceModule", "Attenedance-july2026")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("put|/api/attendance/week-offs/update/1|attenedance-july2026|weekoffupdate", name="API Identifier")
def test_attenedance_july2026_api_attendance_week_offs_update_1_status_code(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "PUT")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/week-offs/update/1")
    allure.dynamic.parameter("Expected Status", "200")
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


@allure.title("Week Off Update \u2014 response matches documented schema")
@allure.epic("Attenedance-july2026")
@allure.feature("PUT /api/attendance/week-offs/update/1 — WeekOffUpdate")
@allure.story("OpenAPI Schema Validation Check")
@allure.parent_suite("Attenedance-july2026")
@allure.suite("PUT /api/attendance/week-offs/update/1 — WeekOffUpdate")
@allure.sub_suite("OpenAPI Schema Validation Check")
@allure.label("sourceModule", "Attenedance-july2026")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("put|/api/attendance/week-offs/update/1|attenedance-july2026|weekoffupdate", name="API Identifier")
def test_attenedance_july2026_api_attendance_week_offs_update_1_response_schema(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "PUT")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/week-offs/update/1")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
