"""Generated tests for API row 6.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "6",
  "Module Name": "Leave API",
  "Sub-Module Name": "TC02 - Invalid token returns observed authorization status",
  "Access": "private",
  "Functional Purpose": "TC02 - Invalid token returns observed HTTP 401; TC02 - Full response matches OpenAPI GetAllLeaveReportsErrorResponse; TC02 - Invalid token response has observed error structure",
  "Base URL": "{{leaveBaseUrl}}",
  "Endpoint / Path": "/user/leaves/getAllLeaveReports",
  "HTTP Method": "GET",
  "Request Parameters": "query: month=4; year=2026 | headers: Authorization=Bearer invalid-token-value",
  "Request Body": "",
  "Example Request Payload": "",
  "Request Body Schema": "",
  "Response (example/200)": "Expected status(es): 401\n{\n  \"token\": \"<jwt-token>\"\n}",
  "Example Response Payload": "{\n  \"token\": \"<jwt-token>\"\n}",
  "Dependent APIs / Services": "",
  "Owner / Developer": "",
  "API Identifier": "get|{{leavebaseurl}}|/user/leaves/getallleavereports|leave api|tc02 - invalid token returns observed authorization status",
  "Comments": "Source: collections/Leave_API.json; Data-driven: test-data/Leave_API.csv; No saved response example in source file"
}""")

@allure.title("TC02 - Invalid token returns observed authorization status \u2014 returns HTTP 401")
@allure.epic("Leave API")
@allure.feature("GET /user/leaves/getAllLeaveReports — TC02 - Invalid token returns observed authorization status")
@allure.story("HTTP Status Code Check (401)")
@allure.parent_suite("Leave API")
@allure.suite("GET /user/leaves/getAllLeaveReports — TC02 - Invalid token returns observed authorization status")
@allure.sub_suite("HTTP Status Code Check (401)")
@allure.label("sourceModule", "Leave API")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("get|{{leavebaseurl}}|/user/leaves/getallleavereports|leave api|tc02 - invalid token returns observed authorization status", name="API Identifier")
@pytest.mark.skip(reason="Temporarily disabled per user request due to negative scenario mismatch")
def test_leave_api_user_leaves_getallleavereports_status_code(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "GET")
    allure.dynamic.parameter("Endpoint Path", "/user/leaves/getAllLeaveReports")
    allure.dynamic.parameter("Expected Status", "401")
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 401


@allure.title("TC02 - Invalid token returns observed authorization status \u2014 response matches documented schema")
@allure.epic("Leave API")
@allure.feature("GET /user/leaves/getAllLeaveReports — TC02 - Invalid token returns observed authorization status")
@allure.story("OpenAPI Schema Validation Check")
@allure.parent_suite("Leave API")
@allure.suite("GET /user/leaves/getAllLeaveReports — TC02 - Invalid token returns observed authorization status")
@allure.sub_suite("OpenAPI Schema Validation Check")
@allure.label("sourceModule", "Leave API")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("get|{{leavebaseurl}}|/user/leaves/getallleavereports|leave api|tc02 - invalid token returns observed authorization status", name="API Identifier")
@pytest.mark.skip(reason="Temporarily disabled per user request due to negative scenario mismatch")
def test_leave_api_user_leaves_getallleavereports_response_schema(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "GET")
    allure.dynamic.parameter("Endpoint Path", "/user/leaves/getAllLeaveReports")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 401
    assert_response_matches_schema(response, API)
