"""Generated tests for API row 3.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "3",
  "Module Name": "Leave API",
  "Sub-Module Name": "TC03 - Pending approvals returns pendingleavs array",
  "Access": "private",
  "Functional Purpose": "TC03 - Status is 200; TC03 - Response has pendingleavs array; TC03 - Response time under 5000ms; TC03 - Record has all required fields; TC03 - leave_count is a positive number; TC03 - approver_type is Administrative or Functional; TC03 - leave_type is a known value",
  "Base URL": "{{leaveBaseUrl}}",
  "Endpoint / Path": "/user/leaves/approvals",
  "HTTP Method": "GET",
  "Request Parameters": "headers: Authorization=Bearer {{authToken}}",
  "Request Body": "",
  "Example Request Payload": "",
  "Request Body Schema": "",
  "Response (example/200)": "Expected status(es): 200\n{\n  \"pendingleavs\": []\n}",
  "Example Response Payload": "{\n  \"pendingleavs\": []\n}",
  "Dependent APIs / Services": "Requires authToken from Login API; Depends on Login API POST /auth/token for authToken",
  "Owner / Developer": "KavishTadas <kavish.tadas@omfysgroup.com>",
  "API Identifier": "get|{{leavebaseurl}}|/user/leaves/approvals|leave api|tc03 - pending approvals returns pendingleavs array",
  "Comments": "Source: collections/Leave_API.json; Data-driven: test-data/Leave_API.csv; No saved response example in source file"
}""")

def test_leave_api_user_leaves_approvals_status_code(api_runtime_config: dict[str, str]) -> None:
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


def test_leave_api_user_leaves_approvals_response_schema(api_runtime_config: dict[str, str]) -> None:
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
