"""Generated tests for API row 1.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "1",
  "Module Name": "Leave API",
  "Sub-Module Name": "TC01 - Show leave report returns records array",
  "Access": "private",
  "Functional Purpose": "TC01 - Show leave report returns records array",
  "Base URL": "{{leaveBaseUrl}}",
  "Endpoint / Path": "/user/leaves/showleavereport",
  "HTTP Method": "POST",
  "Request Parameters": "headers: Content-Type=application/json; Authorization=Bearer {{authToken}}",
  "Request Body": "{\"startDate\":\"{{startDate}}\",\"endDate\":\"{{endDate}}\"}",
  "Example Request Payload": "{\n  \"startDate\": \"2020-01-01\",\n  \"endDate\": \"2026-12-31\"\n}",
  "Request Body Schema": "{\"startDate\":\"string\",\"endDate\":\"string\"}",
  "Response (example/200)": "Expected status(es): 200\n{\n  \"records\": []\n}",
  "Example Response Payload": "{\n  \"records\": []\n}",
  "Dependent APIs / Services": "Requires authToken from Login API; Depends on Login API POST /auth/token for authToken",
  "Owner / Developer": "KavishTadas <kavish.tadas@omfysgroup.com>",
  "API Identifier": "post|{{leavebaseurl}}|/user/leaves/showleavereport|leave api|tc01 - show leave report returns records array",
  "Comments": "Source: collections/Leave_API.json; Data-driven: test-data/Leave_API.csv; No saved response example in source file"
}""")

def test_leave_api_user_leaves_showleavereport_status_code(api_runtime_config: dict[str, str]) -> None:
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


def test_leave_api_user_leaves_showleavereport_response_schema(api_runtime_config: dict[str, str]) -> None:
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
