"""Generated tests for API row 2.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "2",
  "Module Name": "Leave API",
  "Sub-Module Name": "TC02 - Show leave report rejects missing auth",
  "Access": "private",
  "Functional Purpose": "TC02 - Status is 401 or 403 without token",
  "Base URL": "{{leaveBaseUrl}}",
  "Endpoint / Path": "/user/leaves/showleavereport",
  "HTTP Method": "POST",
  "Request Parameters": "headers: Content-Type=application/json",
  "Request Body": "{\n  \"startDate\": \"2020-01-01\",\n  \"endDate\": \"2026-12-31\"\n}",
  "Example Request Payload": "{\n  \"startDate\": \"2020-01-01\",\n  \"endDate\": \"2026-12-31\"\n}",
  "Request Body Schema": "{\"startDate\":\"string\",\"endDate\":\"string\"}",
  "Response (example/200)": "Expected status(es): 401, 403",
  "Example Response Payload": "",
  "Dependent APIs / Services": "",
  "Owner / Developer": "KavishTadas <kavish.tadas@omfysgroup.com>",
  "API Identifier": "post|{{leavebaseurl}}|/user/leaves/showleavereport|leave api|tc02 - show leave report rejects missing auth",
  "Comments": "Source: collections/Leave_API.json; Data-driven: test-data/Leave_API.csv; No saved response example in source file"
}""")

pytestmark = pytest.mark.skip(reason="API row documents a non-200 or negative scenario, not a valid request")

def test_leave_api_user_leaves_showleavereport_status_code(api_runtime_config: dict[str, str]) -> None:
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


def test_leave_api_user_leaves_showleavereport_response_schema(api_runtime_config: dict[str, str]) -> None:
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
