"""Generated tests for API row 5.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "5",
  "Module Name": "Leave API",
  "Sub-Module Name": "TC01/TC03 - Get all leave reports and validate structure",
  "Access": "private",
  "Functional Purpose": "TC01 - Status is 200 - ; TC01 - Response has status, message, data.count and data.leaveReport - ; TC01 - Count contains observed integer fields - ; TC03 - First two records contain all 13 expected fields - ; TC03 - At least two records available for required spot-check - ; TC04 - Invalid month returns observed error structure -",
  "Base URL": "{{leaveBaseUrl}}",
  "Endpoint / Path": "/user/leaves/getAllLeaveReports",
  "HTTP Method": "GET",
  "Request Parameters": "query: month={{month}}; year={{year}} | headers: Authorization=Bearer {{authToken}}",
  "Request Body": "",
  "Example Request Payload": "",
  "Request Body Schema": "",
  "Response (example/200)": "Expected status(es): 200\n{\n  \"status\": \"<status>\",\n  \"message\": \"<message>\",\n  \"data\": {\n    \"count\": {\n      \"rejected\": 0,\n      \"cancelled\": 0,\n      \"pending\": 0,\n      \"approved\": 0\n    },\n    \"leaveReport\": []\n  }\n}",
  "Example Response Payload": "{\n  \"status\": \"<status>\",\n  \"message\": \"<message>\",\n  \"data\": {\n    \"count\": {\n      \"rejected\": 0,\n      \"cancelled\": 0,\n      \"pending\": 0,\n      \"approved\": 0\n    },\n    \"leaveReport\": []\n  }\n}",
  "Dependent APIs / Services": "Requires authToken from Employee Auth API; Depends on Employee Auth API POST /auth/token for authToken",
  "Owner / Developer": "KavishTadas <kavish.tadas@omfysgroup.com>",
  "API Identifier": "get|{{leavebaseurl}}|/user/leaves/getallleavereports|leave api|tc01/tc03 - get all leave reports and validate structure",
  "Comments": "Source: collections/Leave_API.json; Data-driven: test-data/Leave_API.csv; No saved response example in source file"
}""")

@allure.epic("Leave API")
@allure.feature("Leave API APIs")
@allure.story("GET /user/leaves/getAllLeaveReports")
def test_leave_api_user_leaves_getallleavereports_status_code(api_runtime_config: dict[str, str]) -> None:
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


@allure.epic("Leave API")
@allure.feature("Leave API APIs")
@allure.story("GET /user/leaves/getAllLeaveReports")
def test_leave_api_user_leaves_getallleavereports_response_schema(api_runtime_config: dict[str, str]) -> None:
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
