"""Generated tests for API row 7.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "7",
  "Module Name": "Attendance Policy Master",
  "Sub-Module Name": "Create New Policy",
  "Access": "private",
  "Functional Purpose": "Create New Policy",
  "Base URL": "{{baseURL}}",
  "Endpoint / Path": "/api/attendancepolicy",
  "HTTP Method": "POST",
  "Request Parameters": "headers: Authorization=Bearer {{authToken}}",
  "Request Body": "{\n    \"policyName\": \"Late Coming\",\n    \"policyHeading\":\"Late Coming Policy Heading\",\n    \"policyDescription\":\"Late Coming Policy Description\"\n}",
  "Example Request Payload": "{\n  \"policyName\": \"Late Coming\",\n  \"policyHeading\": \"Late Coming Policy Heading\",\n  \"policyDescription\": \"Late Coming Policy Description\"\n}",
  "Request Body Schema": "{\"policyName\":\"string\",\"policyHeading\":\"string\",\"policyDescription\":\"string\"}",
  "Response (example/200)": "",
  "Example Response Payload": "",
  "Dependent APIs / Services": "Requires authToken from Employee Auth API; Depends on Employee Auth API POST /auth/token for authToken",
  "Owner / Developer": "",
  "API Identifier": "post|/api/attendancepolicy|attendance policy master|create new policy",
  "Comments": "Source: collections/Attendance_Management_API.json; No saved response example in source file"
}""")

@allure.title("Create New Policy \u2014 returns HTTP 200")
@allure.epic("Attendance Policy Master")
@allure.feature("POST /api/attendancepolicy — Create New Policy")
@allure.story("HTTP Status Code Check (200)")
@allure.parent_suite("Attendance Policy Master")
@allure.suite("POST /api/attendancepolicy — Create New Policy")
@allure.sub_suite("HTTP Status Code Check (200)")
@allure.label("sourceModule", "Attendance Policy Master")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("post|/api/attendancepolicy|attendance policy master|create new policy", name="API Identifier")
def test_attendance_policy_master_api_attendancepolicy_status_code(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "POST")
    allure.dynamic.parameter("Endpoint Path", "/api/attendancepolicy")
    allure.dynamic.parameter("Expected Status", "200")
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


@allure.title("Create New Policy \u2014 response matches documented schema")
@allure.epic("Attendance Policy Master")
@allure.feature("POST /api/attendancepolicy — Create New Policy")
@allure.story("OpenAPI Schema Validation Check")
@allure.parent_suite("Attendance Policy Master")
@allure.suite("POST /api/attendancepolicy — Create New Policy")
@allure.sub_suite("OpenAPI Schema Validation Check")
@allure.label("sourceModule", "Attendance Policy Master")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "")
@allure.link("post|/api/attendancepolicy|attendance policy master|create new policy", name="API Identifier")
def test_attendance_policy_master_api_attendancepolicy_response_schema(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "POST")
    allure.dynamic.parameter("Endpoint Path", "/api/attendancepolicy")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
