"""Generated tests for API row 45.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "45",
  "Module Name": "Holiday Template APIs Copy",
  "Sub-Module Name": "Delete",
  "Access": "private",
  "Functional Purpose": "Delete",
  "Base URL": "{{baseURL}}",
  "Endpoint / Path": "/api/attendance/holiday-templates/delete/{holidayTemplateId}",
  "HTTP Method": "DELETE",
  "Request Parameters": "path variables: holidayTemplateId=999999 | headers: Authorization=Bearer {{jwtToken}}",
  "Request Body": "",
  "Example Request Payload": "",
  "Request Body Schema": "",
  "Response (example/200)": "",
  "Example Response Payload": "",
  "Dependent APIs / Services": "",
  "Owner / Developer": "Parth Divekar <parthdivekar987@gmail.com>",
  "API Identifier": "delete|/api/attendance/holiday-templates/delete/{holidaytemplateid}|holiday template apis copy|delete",
  "Comments": "Source: collections/Holiday_Template_API.json; No saved response example in source file"
}""")

@allure.title("Delete \u2014 returns HTTP 200")
@allure.epic("Holiday Template APIs Copy")
@allure.feature("DELETE /api/attendance/holiday-templates/delete/{holidayTemplateId} — Delete")
@allure.story("HTTP Status Code Check (200)")
@allure.parent_suite("Holiday Template APIs Copy")
@allure.suite("DELETE /api/attendance/holiday-templates/delete/{holidayTemplateId} — Delete")
@allure.sub_suite("HTTP Status Code Check (200)")
@allure.label("sourceModule", "Holiday Template APIs Copy")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "Parth Divekar <parthdivekar987@gmail.com>")
@allure.link("delete|/api/attendance/holiday-templates/delete/{holidaytemplateid}|holiday template apis copy|delete", name="API Identifier")
def test_holiday_template_apis_copy_api_attendance_holiday_templates_delete_holidaytemplateid_status_code(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "DELETE")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/holiday-templates/delete/{holidayTemplateId}")
    allure.dynamic.parameter("Expected Status", "200")
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


@allure.title("Delete \u2014 response matches documented schema")
@allure.epic("Holiday Template APIs Copy")
@allure.feature("DELETE /api/attendance/holiday-templates/delete/{holidayTemplateId} — Delete")
@allure.story("OpenAPI Schema Validation Check")
@allure.parent_suite("Holiday Template APIs Copy")
@allure.suite("DELETE /api/attendance/holiday-templates/delete/{holidayTemplateId} — Delete")
@allure.sub_suite("OpenAPI Schema Validation Check")
@allure.label("sourceModule", "Holiday Template APIs Copy")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "Parth Divekar <parthdivekar987@gmail.com>")
@allure.link("delete|/api/attendance/holiday-templates/delete/{holidaytemplateid}|holiday template apis copy|delete", name="API Identifier")
def test_holiday_template_apis_copy_api_attendance_holiday_templates_delete_holidaytemplateid_response_schema(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "DELETE")
    allure.dynamic.parameter("Endpoint Path", "/api/attendance/holiday-templates/delete/{holidayTemplateId}")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
