"""Generated tests for API row 6.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import pytest

from ._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{
  "Sr. No": "6",
  "Module Name": "auth",
  "Sub-Module Name": "Login",
  "Access": "public",
  "Functional Purpose": "Status is 200; Token exists",
  "Base URL": "{{BASE_URL}}",
  "Endpoint / Path": "/auth/login",
  "HTTP Method": "POST",
  "Request Parameters": "",
  "Request Body": "{ \"email\": \"{{USERNAME}}\", \"password\": \"{{PASSWORD}}\" }",
  "Example Request Payload": "{\n  \"email\": \"<USERNAME>\",\n  \"password\": \"<PASSWORD>\"\n}",
  "Request Body Schema": "{\"email\":\"string\",\"password\":\"string\"}",
  "Response (example/200)": "Expected status(es): 200\n{\n  \"token\": \"<jwt-token>\"\n}",
  "Example Response Payload": "{\n  \"token\": \"<jwt-token>\"\n}",
  "Dependent APIs / Services": "Produces authToken for downstream APIs",
  "Owner / Developer": "KavishTadas <kavish.tadas@omfysgroup.com>",
  "API Identifier": "post|{{base_url}}|/auth/login|auth|login",
  "Comments": "Source: bruno/auth/login.bru; No saved response example in source file; Parsed from Bruno file"
}""")

def test_auth_auth_login_status_code(api_runtime_config: dict[str, str]) -> None:
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200


def test_auth_auth_login_response_schema(api_runtime_config: dict[str, str]) -> None:
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == 200
    assert_response_matches_schema(response, API)
