allure.results.directory=reports/allure-results
allure.report.directory=reports/allure-report
allure.link.issue.pattern=https://jira.yourcompany.com/browse/{}
allure.link.tms.pattern=https://jira.yourcompany.com/browse/{}
