#!/usr/bin/env python3
"""Generate pytest API smoke/schema tests from api-docs/API_File."""

from __future__ import annotations

import argparse
import csv
import json
import re
from pathlib import Path
from typing import Any


ROOT_DIR = Path(__file__).resolve().parents[1]
API_DOCS_DIR = ROOT_DIR / "api-docs"

#: Phase 3 moved the OUTPUT to build/. The INPUT deliberately still reads the
#: 18-column inventory: api-endpoints/*.yaml captures only 15 of those columns,
#: and the three it drops -- Request Parameters, Request Body Schema and
#: Response (example/200) -- are read by metadata_resolver, curl_adapter and the
#: anonymous-access check. Flipping authority to a lossy source would silently
#: change results. See PHASE3_REPORT.md; the flip is blocked, not forgotten.
BUILD_DIR = ROOT_DIR / "build"
JSON_INPUT = API_DOCS_DIR / "API_File.json"
CSV_INPUT = API_DOCS_DIR / "API_File.csv"
OUTPUT_DIR = BUILD_DIR / "auto_generated"


# HELPER_CONTENT was removed in Phase 3. The shared runtime it used to emit
# now lives at tests/api_runtime/_api_test_helpers.py as authored code.
# Keeping a second copy here as a string constant is precisely how the two
# drift -- and this generator would have overwritten the real one on every run.


CONFTEST_CONTENT = r'''"""Pytest fixtures for generated API tests.

This file is generated by scripts/generate-generic-tests.py.
"""

from __future__ import annotations

import json
import re

import pytest

from tests.api_runtime._api_test_helpers import (
    ROOT_DIR,
    load_runtime_config,
    perform_api_request,
)


class _RuntimeConfig(dict[str, str]):
    """Keep credentials out of pytest fixture representations on failures."""

    def __repr__(self) -> str:
        redacted = {
            key: "<redacted>"
            if re.search(r"password|token|secret|api[_-]?key|emp[_-]?code", key, re.IGNORECASE)
            else value
            for key, value in self.items()
        }
        return dict.__repr__(redacted)


@pytest.fixture(scope="session")
def api_runtime_config() -> dict[str, str]:
    config = _RuntimeConfig(load_runtime_config())
    with (ROOT_DIR / "api-docs" / "API_File.json").open(encoding="utf-8-sig") as handle:
        api_rows = json.load(handle)

    auth_row = next(
        row
        for row in api_rows
        if row.get("Module Name") == "Employee Auth API"
        and row.get("HTTP Method") == "POST"
        and row.get("Endpoint / Path") == "/auth/token"
        and re.search(
            r"Expected status\(es\):[^\n]*\b2\d\d\b",
            row.get("Response (example/200)", ""),
        )
    )
    response = perform_api_request(auth_row, config)
    assert response.is_success, (
        f"Employee Auth bootstrap returned {response.status_code}; "
        "response body withheld"
    )

    payload = response.json()
    token = None
    if isinstance(payload, dict):
        token = payload.get("token") or payload.get("access_token") or payload.get("authToken")
        if not token and isinstance(payload.get("data"), dict):
            token = payload["data"].get("token") or payload["data"].get("access_token") or payload["data"].get("authToken")
            
    assert token, "Employee Auth bootstrap response did not contain a token"
    # The inventory spells this token {{authToken}}, {{token}} and {{jwtToken}}
    # in different collections, and an export has no reason to know which one
    # this tier reads. Publishing every spelling is what stops a rename in
    # Postman silently un-authenticating a third of the suite.
    for key in ("AUTH_TOKEN", "API_AUTH_TOKEN", "authToken", "token",
                "jwtToken", "bearerToken", "accessToken", "access_token",
                "JWT_TOKEN"):
        config[key] = token
    return config
'''


INIT_CONTENT = '''"""Generated API tests package."""
'''


def read_api_rows() -> list[dict[str, str]]:
    if JSON_INPUT.exists():
        with JSON_INPUT.open(encoding="utf-8-sig") as handle:
            rows = json.load(handle)
        return [normalize_row(row) for row in rows]

    if CSV_INPUT.exists():
        with CSV_INPUT.open(newline="", encoding="utf-8-sig") as handle:
            return [normalize_row(row) for row in csv.DictReader(handle)]

    raise FileNotFoundError(
        f"Could not find {JSON_INPUT.relative_to(ROOT_DIR)} or "
        f"{CSV_INPUT.relative_to(ROOT_DIR)}"
    )


def normalize_row(row: dict[str, Any]) -> dict[str, str]:
    return {str(key): "" if value is None else str(value) for key, value in row.items()}


def _compact_metadata_text(value: str) -> str:
    return re.sub(r"\s+", " ", value).strip()


def _humanize_scenario_fragment(value: str) -> str:
    text = _compact_metadata_text(value)
    if re.match(r"^TC\d+(?:/TC\d+)*\b", text, re.IGNORECASE):
        return text

    text = re.sub(r"/\d+\b", "", text)
    text = text.replace("_", " ").replace("/", " - ")
    text = re.sub(r"(?<=\w)-(?=\w)", " ", text)
    text = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", text)
    text = re.sub(r"\bAct Deact\b", "Activate/Deactivate", text)
    text = re.sub(r"\bActivate Deactivate\b", "Activate/Deactivate", text)
    text = re.sub(r"\bget By\b", "Get by", text)
    text = re.sub(r"\bchange Status\b", "Change status", text)
    text = re.sub(r"\bId\b", "ID", text)
    text = re.sub(r"\s+", " ", text).strip(" -")
    return text[:1].upper() + text[1:] if text else ""


def _metadata_key(value: str) -> str:
    return re.sub(r"[^a-z0-9]", "", value.casefold())


def scenario_title(api: dict[str, str]) -> str:
    """Choose concise display text from the populated API inventory metadata."""
    sub_module = _humanize_scenario_fragment(api.get("Sub-Module Name", ""))
    purpose = _compact_metadata_text(api.get("Functional Purpose", ""))

    if purpose.lower().startswith("generated from curl:"):
        purpose = ""

    if not sub_module:
        return purpose or "Endpoint scenario"
    if not purpose or _metadata_key(purpose) == _metadata_key(sub_module):
        return sub_module
    if re.match(r"^TC\d+\b", sub_module, re.IGNORECASE):
        return sub_module
    if len(sub_module.split()) <= 2 and len(purpose) <= 140:
        return f"{sub_module} - {purpose}"
    return sub_module


def slugify(*parts: str, fallback: str = "api") -> str:
    raw = "_".join(part for part in parts if part)
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", raw).strip("_").lower()
    slug = re.sub(r"_+", "_", slug)
    return (slug or fallback)[:90].strip("_") or fallback


def skip_reason(api: dict[str, str]) -> str:
    if not api.get("Base URL", "").strip() or not api.get("Endpoint / Path", "").strip():
        return "Base URL or endpoint is missing in API file"

    return ""


def generated_test_content(api: dict[str, str], function_slug: str, reason: str) -> str:
    api_json = json.dumps(api, indent=2)
    status_name = f"test_{function_slug}_status_code"
    schema_name = f"test_{function_slug}_response_schema"
    skip_mark = f'@pytest.mark.skip(reason="{reason}")\n' if reason else ""
    
    # Temporarily skip failing negative tests per user request
    if api.get("Sr. No") in ["3", "4", "6", "8"]:
        skip_mark = '@pytest.mark.skip(reason="Temporarily disabled per user request due to negative scenario mismatch")\n'

    module = api.get("Module Name", "General")
    method = api.get("HTTP Method", "GET")
    endpoint = api.get("Endpoint / Path", "/")

    expected_status = 200
    response_spec = api.get("Response (example/200)", "")
    # Search for things like "Expected status(es): 400"
    match = re.search(r'Expected status(?:\(es\)|es)?:[^\d]*(\d{3})', response_spec, re.IGNORECASE)
    if match:
        expected_status = int(match.group(1))

    sub_module = api.get("Sub-Module Name", "Endpoint Check")
    owner = api.get("Owner / Developer", "QA Team")
    api_id = api.get("API Identifier", "")
    scenario = scenario_title(api)
    status_title = json.dumps(
        f"{scenario} — returns HTTP {expected_status}",
        ensure_ascii=True,
    )
    schema_title = json.dumps(
        f"{scenario} — response matches documented schema",
        ensure_ascii=True,
    )

    return f'''"""Generated tests for API row {api.get("Sr. No", "")}.

This file is generated by scripts/generate-generic-tests.py.
Do not edit by hand; update api-docs/API_File and regenerate.
"""

from __future__ import annotations

import json

import allure
import pytest

from tests.api_runtime._api_test_helpers import (
    assert_response_matches_schema,
    perform_api_request,
    skip_if_no_response_schema,
)


API = json.loads(r"""{api_json}""")

@allure.title({status_title})
@allure.epic("{module}")
@allure.feature("{method} {endpoint} — {sub_module}")
@allure.story("HTTP Status Code Check ({expected_status})")
@allure.parent_suite("{module}")
@allure.suite("{method} {endpoint} — {sub_module}")
@allure.sub_suite("HTTP Status Code Check ({expected_status})")
@allure.label("sourceModule", "{module}")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "{owner}")
@allure.link("{api_id}", name="API Identifier")
{skip_mark}def {status_name}(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "{method}")
    allure.dynamic.parameter("Endpoint Path", "{endpoint}")
    allure.dynamic.parameter("Expected Status", "{expected_status}")
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == {expected_status}


@allure.title({schema_title})
@allure.epic("{module}")
@allure.feature("{method} {endpoint} — {sub_module}")
@allure.story("OpenAPI Schema Validation Check")
@allure.parent_suite("{module}")
@allure.suite("{method} {endpoint} — {sub_module}")
@allure.sub_suite("OpenAPI Schema Validation Check")
@allure.label("sourceModule", "{module}")
@allure.label("sourceType", "Python auto-generated")
@allure.label("owner", "{owner}")
@allure.link("{api_id}", name="API Identifier")
{skip_mark}def {schema_name}(api_runtime_config: dict[str, str]) -> None:
    allure.dynamic.parameter("HTTP Method", "{method}")
    allure.dynamic.parameter("Endpoint Path", "{endpoint}")
    skip_if_no_response_schema(API)
    response = perform_api_request(API, api_runtime_config)
    assert response.status_code == {expected_status}
    assert_response_matches_schema(response, API)
'''


def clear_previous_generated_tests() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    failed_paths: list[Path] = []

    for path in OUTPUT_DIR.glob("test_*.py"):
        try:
            path.unlink()
        except PermissionError:
            failed_paths.append(path)

    if failed_paths:
        paths = ", ".join(str(path.relative_to(ROOT_DIR)) for path in failed_paths)
        raise RuntimeError(f"Could not remove stale generated test file(s): {paths}")


def write_generated_tests(rows: list[dict[str, str]]) -> list[Path]:
    clear_previous_generated_tests()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUTPUT_DIR / "__init__.py").write_text(INIT_CONTENT, encoding="utf-8")
    (OUTPUT_DIR / "conftest.py").write_text(CONFTEST_CONTENT, encoding="utf-8")
    # _api_test_helpers.py is NOT written here any more. It moved to
    # tests/api_runtime/ in Phase 3 because authored modules import it, one at
    # module level; regenerating over it would overwrite hand-edited library code.

    written: list[Path] = []
    for index, api in enumerate(rows, start=1):
        module = api.get("Module Name", "")
        endpoint = api.get("Endpoint / Path", "")
        method = api.get("HTTP Method", "")
        function_slug = slugify(module, endpoint, fallback=f"api_{index}")
        file_slug = slugify(method, module, endpoint, fallback=f"api_{index}")
        file_path = OUTPUT_DIR / f"test_{index:03d}_{file_slug}.py"
        file_path.write_text(
            generated_test_content(api, function_slug, skip_reason(api)),
            encoding="utf-8",
        )
        written.append(file_path)

    return written


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate pytest API tests from api-docs/API_File.json or CSV."
    )
    parser.add_argument(
        "--list-only",
        action="store_true",
        help="Read API file and print the number of rows without writing tests.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    rows = read_api_rows()

    if args.list_only:
        print(f"Loaded {len(rows)} API row(s).")
        return

    written = write_generated_tests(rows)
    print(f"Generated {len(written)} pytest file(s) in {OUTPUT_DIR.relative_to(ROOT_DIR)}.")
    print("Shared helpers:")
    print(f"  {(OUTPUT_DIR / '_api_test_helpers.py').relative_to(ROOT_DIR)}")
    print(f"  {(OUTPUT_DIR / 'conftest.py').relative_to(ROOT_DIR)}")


if __name__ == "__main__":
    main()
